### ISSUE TITLE
Daphne should use Twisted's strports/serverFromString for TLS/ACME support

### ISSUE THREAD

**Issue by hawkowl** [django/daphne#10]
This would replace this code (https://github.com/andrewgodwin/daphne/blob/master/daphne/server.py#L46) with a user passing a strports description on the command line, which is fed into http://twistedmatrix.com/documents/current/api/twisted.internet.endpoints.html#serverFromString. For example, to support unix sockets it would be `unix:/var/run/finger`, for TCP it'd be `tcp:8000`, for basic TLS it would be `ssl:443:privateKey=key.pem:certKey=crt.pem`, for txsni (TLS w/ SNI) it would be `txsni:certificates:tcp:443`, and for the automatic, turn-on TLS+SNI, it would be `le:/srv/www/certs:tcp:443` (https://github.com/mithrandi/txacme).

I'm happy to implement this, but I thought I'd file an issue since it's been on my mind for so long :)

**Comment by andrewgodwin** [comment]
Sounds good to me! We should keep the `--unix-socket` arg around for a little bit too and make it raise an error saying what to do instead.

**Comment by mcallistersean** [comment]
Now that #37 has landed in master I guess this should JustWork™

I haven't actually found a combination of txacme/txsni that actually works for me, but using 
`
daphne -e lets:/path/to/certs:tcp:interface=<interface_address>:port=443 channel layer project.asgi:channel_layer
`
actually listens on port 443 and tries to get a certificate (at which point it fails). Don't have the time to debug this right now but would like to hear about some success stories.

**Comment by mcallistersean** [comment]
Hi Ameber,
yes, I'm aware of that.
I have a DNs entry pointed to my development machine, port forwarding is in place and it the daphne server is reachable from the outside using the domain name.
Did you manage to get it working and if yes, which versions?
There are also some problems with python3 in txsni.

**Comment by mcallistersean** [comment]
With recent checkouts of txacme and txsni and some patches for py3 compatibility I got lets: endpoints working. But this has nothing to do with daphne anymore, so I guess this issue can be closed.

**Comment by andrewgodwin** [comment]
I've definitely found ACME to be a little bit picky before when doing my own dev, but good to have confirmation it works. I'll close this, but we should get some docs done about it too.

**Comment by fuzzy76** [comment]
Does this mean that Daphne supports HTTPS or not? I have been searching both documentation and issue queue for something definite.

**Comment by andrewgodwin** [comment]
It does, you have to just use Twisted endpoint syntax and pass it to Daphne using the `-e` switch. For example:

   daphne -e ssl:port=443:privateKey=/etc/ssl/server.pem:extraCertChain=/etc/ssl/chain.pem:sslmethod=SSLv3_METHOD:dhParameters=dh_param_1024.pem

More docs on this here: https://twistedmatrix.com/documents/16.4.1/core/howto/endpoints.html#servers - though there are other things you can do with Twisted endpoints that aren't there, like let's encrypt support.

**Comment by davidmarquis** [comment]
Also explained pretty clearly on the Daphne README: https://github.com/django/daphne (look for "SSL" on the page)
