### ISSUE TITLE
daphne==1.2.0 hangs forever

### ISSUE THREAD

**Issue by javiermatos** [django/daphne#105]
I actually have a web application which works with daphne==1.1.0 but hangs when I update to daphne==1.2.0. The rest of the packages are the same.

asgi_ipc==1.2.0  # Develop environment
asgi_redis==1.0.0  # production environment
asgiref==1.1.1
channels==1.1.2
daphne==1.1.0  # works with 1.1.0 but fails with 1.2.0
django==1.11.0

With daphne==1.1.0 it is working fine. With daphne==1.2.0 it hangs forever when trying to go to admin page (or any other page processed by django). It hangs on line 92 in file channels/worker.py (channel package). The only difference between working and not working is daphne 1.1.0 vs 1.2.0.

**Comment by proofit404** [comment]
Try to update your redis layer.

**Comment by javiermatos** [comment]
asgi_ipc==1.3.1 # Develop environment
asgi_redis==1.2.1 # Production environment
asgiref==1.1.1
channels==1.1.2
daphne==1.2.0
django==1.11.0

Not it works in development and production environments. I forgot to update asgi_ipc and asgi_redis, sorry. Thank you so much for your help!

**Comment by proofit404** [comment]
@andrewgodwin Do you think we should set maximum release version of channels in layers setup.py dependencies to prevent partial upgrade in the future?

**Comment by andrewgodwin** [comment]
@proofit404 Unfortunately, I don't want to make channels depend on a specific layer or vice-versa, so it's hard to enforce. The thing that could perhaps be done is have Channels try to import those packages and check versions at Django startup time, so at least you get an error with `runworker` or `runserver`.

**Comment by proofit404** [comment]
Or maybe we can use `asgiref` package for this. Each channel layer depends on it anyway. And each version of layer implement concret spec version at the same time. So if channels requires modern spec version and user installed layer for previous spec, pip will show error at installation process.

**Comment by andrewgodwin** [comment]
Maybe, though I'd rather keep the weird error-at-import time stuff in the one place, and Channels will need to check for specific Daphne versions anyway (and something feels wrong about putting it in `asgiref`)

**Comment by andrewgodwin** [comment]
I've implemented a version checker in https://github.com/django/channels/commit/ceeacdbfc33c2f1eb9d219d8bd539ef5e6c4c877
