### ISSUE TITLE
Problem with ssl

### ISSUE THREAD

**Issue by yaslim** [django/daphne#106]
Hello,

I have a website accesible only via HTTPS.
I have this error : 

**WebSocket connection to 'wss://projup.com/notifs/' failed: Error during WebSocket handshake: Unexpected response code: 502** 

**The code for create the websocket :** 

var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";			
var ws_path = ws_scheme + '://' + window.location.host + '/notifs' + window.location.pathname;			
var socket = new WebSocket(ws_path);

In background, **these commands are being executed** (with screen) :

python3.5 manage.py runworker
daphne -p <port_number> projup.asgi:channel_layer

<port_number> = number of the port attributed to and application dedicated to websocket 

I think there is a mistake in the command "daphne -p ..." because now I am using HTTPS only.

**routing.py :** 

channel_routing = [
    route("websocket.connect", ws_connect),
    route("websocket.receive", ws_message),
    route("websocket.disconnect", ws_disconnect),
    route("send-mail", send_notif_mail),
]

**consumers.py :** 

...
@channel_session_user_from_http
def ws_connect(message) :
   ...

@channel_session
def ws_message(message) :
....

@channel_session_user
def ws_disconnect(message) :
...

def send_notif_mail(message):
...

**Where Have I did mistake(s) ?**

Thank you

**Comment by andrewgodwin** [comment]
502 means that whatever is doing your SSL termination cannot see Daphne - it's a bad gateway error. You need to fix that first and then things should keep working.  I can't help with how your server is setup - sorry! If it is nginx there are examples in some other tickets.

**Comment by yaslim** [comment]
I change the code of websocket creation, now it's : 

var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
var ws_path = 'wss://'+window.location.host+':<port_number>/notifs';
var socket = new WebSocket(ws_path);

<port_number> : number of the port attributed to and application dedicated to websocket

Now the error it's : 

**WebSocket connection to 'wss://projup.com:<port_number>/notifs' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED**

It's an another problem now ?

**Comment by andrewgodwin** [comment]
That means the port you gave is not listening. You probably are talking to the wrong machine.

**Comment by yaslim** [comment]
But I have a doubt about the Daphne command :  

daphne -p <port_number> projup.asgi:channel_layer

_<port_number> = number of the port attributed to and application dedicated to websocket_

Have I not to use "daphne -e" (with pyopenssl) ?

**Comment by ssahilsahil798** [comment]
If it is working on local and using SSL then you are right the error lies in command daphne -p .......
When you switch to SSL command changes to - "daphne ssl:port privatekey:yourpriv.pem ......"
Otherwise the error could also be in Nginx Server block or watever reverse proxy you use. The above command is written in github Readme.md of Daphne. I faced similar issue when switched to HTTPS. Hope it helps. Thank you.
