### ISSUE TITLE
Websocket Connect: Query string is unicode string and URL decoded

### ISSUE THREAD

**Issue by maikhoepfel** [django/daphne#110]
As part of my work on the test suite, I discovered that the query string supplied in a Websocket Connect message is, contrary to what the [spec](https://channels.readthedocs.io/en/stable/asgi/www.html#connection) says, a unicode string, and also appears to be already URL decoded.

Upon first sight, I think removing the call to [unquote](https://github.com/django/daphne/blob/master/daphne/ws_protocol.py#L73) might help. But Andrew also mentioned that query strings are a complex issue and mentioned the related ticket https://github.com/django/channels/issues/210. 

I've created this issue to reference it in the upcoming PR, but unfortunately don't have time to investigate further.

**Comment by andrewgodwin** [comment]
I suspect this is directly related to #108.

**Comment by maikhoepfel** [comment]
Lovely, thanks Andrew. I posted https://github.com/django/daphne/pull/112 as a follow-up. It re-enables the query string section of the tests.

**Comment by andrewgodwin** [comment]
Re-enabled!
