### ISSUE TITLE
How to proxy using apache

### ISSUE THREAD

**Issue by felixcheruiyot** [django/daphne#115]
Struggling on how to use daphne with apache. Here is my vhost setting

<VirtualHost *:80>
    ServerName xxx
    ServerAdmin xxx
    ServerAlias xxxx
    DocumentRoot /var/www/portals/animal

    Alias /static /var/www/portals/animal/staticfiles
    Alias /media /var/www/portals/animal/mediafiles

    <Directory /var/www/portals/animal/staticfiles>
        Require all granted
     </Directory>

    ErrorLog /var/log/livestock.error.log
    CustomLog /var/log/livestock.access.log combined

    ProxyPass /static/ !
    ProxyPass / http://127.0.0.1:8001/
    ProxyPassReverse / http://127.0.0.1:8001/
</VirtualHost>

Problem:
My WebSocket throws a 404 yet the daphne process at http://127.0.0.1:8001 works well.

**Comment by andrewgodwin** [comment]
Apache does not support proxying WebSockets by default. You will need to install the `mod_proxy_wstunnel` module.

**Comment by greysondn** [comment]
Is this really all it takes? Because that would be amazing.

**Comment by partofthething** [comment]
It appears to not be that simple. I have the same config with `mod_proxy_wstunnel` enabled but it does not work. Daphne still throws a 404 for the `ws` target.

**Comment by tablefiller** [comment]
> It appears to not be that simple. I have the same config with `mod_proxy_wstunnel` enabled but it does not work. Daphne still throws a 404 for the `ws` target.

any luck with that? getting the same issue.
