### ISSUE TITLE
Autobahn handshake timeout

### ISSUE THREAD

**Issue by ElRoberto538** [django/daphne#119]
We are currently having issues in our development environment where our database is on a remote machine. The Autobahn ```openHandshakeTimeout``` is set to 5 by default, and with our remote database + a bunch of authentication processing it frequently takes between 5 and 10 seconds to finish the handshake. This is causing the connection to timeout. 

Changing the timeout value passed to ```self.ws_factory.setProtocolOptions``` in daphne/http_protocol.py to 10 seconds fixes this issue and stops Autobahn from disconnecting.

e.g.
```python
self.ws_factory.setProtocolOptions(
        autoPingTimeout=ping_timeout,
        allowNullOrigin=True,
        openHandshakeTimeout=ws_open_handshake_timeout
    )
```

I have made a change to accept a new parameter ```--ws_open_handshake_timeout``` in runserver to pass this parameter through to http_protocol.py - should I submit a pull request for this and if so is this new parameter necessary, or should it be using the ```websocket_connect_timeout``` parameter and then add ```--websocket_connect_timeout``` as an argument to runserver in Channels?

**Comment by andrewgodwin** [comment]
I'm more concerned it's taking 5 seconds to do the handshake - is that Channels' fault in any way, or just that you have a very slow database?

However, yes, I would take a PR to allow people to increase/decrease it.

**Comment by ElRoberto538** [comment]
@andrewgodwin Thanks, I don't believe the performance issue has anything to do with Channels, everything works perfectly in production which is hosted alongside the database. The delay is almost certainly caused by database latency on our end. I will submit a pull request tomorrow to allow the handshake timeout to be configurable.
