### ISSUE TITLE
Chunk large request bodies into multiple http.request.body events

### ISSUE THREAD

**Issue by michalmo** [django/daphne#126]
I've been searching through the code and Channels seems to support reading chunked bodies, but Daphne always sends the whole body in the `http.request` message.
Am i missing something?

**Comment by JohnDoee** [comment]
You seem to be correct and you can probably turn this ticket into a feature request instead.

**Comment by proofit404** [comment]
Yes, you're correct. Daphne doesn't support bodies chunking at this time.

**Comment by andrewgodwin** [comment]
Yup, tagged it as an enhancement. This will probably get a lot easier with the changes I'm proposing to Channels in the near future (http://www.aeracode.org/2017/7/11/towards-channels-20/), so it's likely we'll wait till then to implement it as it'll perform much better.

**Comment by michalmo** [comment]
Thanks, interesting read.

**Comment by andrewgodwin** [comment]
Just to reconfirm that Daphne 2.0 still does not support chunking incoming HTTP bodies, though it's less of a problem as it's now an in-memory dict that gets passed around rather than going over a channel layer. It should still be fixed to read from the client socket progressively, though.

**Comment by mor747111** [comment]
I've encountered this problem lately and I would like to try and solve this issue. Would you say this is currently solvable? Are there any new insights about this issue?

**Comment by andrewgodwin** [comment]
It's solvable, but might already be solved in `uvicorn` if you need it now? I haven't checked recently.

**Comment by JJK-IO** [comment]
Alternatively as the docs in Channels mentions you can route traffic based on traffic type. If you need this up and running for production sites you can route similar to this.

https://serverfault.com/questions/910805/proxy-websockets-and-http-through-the-same-location-in-nginx

Requirements:
Run a daphne server on port 8000
Run a gunicorn server on port 8001

```
map $http_upgrade $type {
  default "web";
  websocket "ws";
}

upstream daphne {
  server: localhost:8000;
}

upstream gunicorn {
  server: localhost:8001
}

server {
  # ...

  location / {
    try_files /nonexistent @$type;
  }

  location @ws {
    ...
    proxy_pass: http://daphne;
  }

  location @web {
    ...
    proxy_pass: http://gunicorn;
  }
}
```
