### ISSUE TITLE
Origin / Headers for disconnect

### ISSUE THREAD

**Issue by tomturner** [django/daphne#130]
I run a project call https://github.com/tomturner/django-tenants which is used for SAAS sites. It allows one to select a PostgrSQL schema based on the subdomain.
My Problem is that the disconnect command and the message command does not have the headers (the origin / subdomain is the header) so I don't know where the request is coming.
I have done a patch where I have added the headers to the disconnect command and the onMessage command. Can I submit the Patch?

**Comment by andrewgodwin** [comment]
I'm afraid I wouldn't take the patch right now - the short term suggestion would be to store information you need in disconnect in the `channel_session`, and in the longer term we're reworking the way Channels runs so you can persist variables etc. through to disconnect as well.

**Comment by tomturner** [comment]
@andrewgodwin that's good one will be able to persist data.Do you know when that is coming?  I believe the session data is stored in the database which means I can't use it as that table is the tennanted

**Comment by andrewgodwin** [comment]
Can't give a timeline unfortunately. Channels is a volunteer project so it depends on spare time.
