### ISSUE TITLE
Trying to understand the given error

### ISSUE THREAD

**Issue by kkar** [django/daphne#143]
Hello, i am getting the following error when running **daphne amanet.asgi:channel_layer -u ../file_sockets/daphne_main_server.sock**

Can somebody help me, please?

> user@user-OptiPlex-GX620:~/main_folder/amanet$ daphne amanet.asgi:channel_layer -u ../file_sockets/daphne_main_server.sock
> /usr/local/lib/python2.7/dist-packages/floppyforms/__init__.py:21: UserWarning: Unable to import floppyforms.gis, geometry widgets not available
>   "Unable to import floppyforms.gis, geometry widgets not available")
> Traceback (most recent call last):
>   File "/usr/local/bin/daphne", line 9, in <module>
>     load_entry_point('daphne==1.3.0', 'console_scripts', 'daphne')()
>   File "/usr/local/lib/python2.7/dist-packages/daphne-1.3.0-py2.7.egg/daphne/cli.py", line 144, in entrypoint
>     cls().run(sys.argv[1:])
>   File "/usr/local/lib/python2.7/dist-packages/daphne-1.3.0-py2.7.egg/daphne/cli.py", line 219, in run
>     self.server.run()
>   File "/usr/local/lib/python2.7/dist-packages/daphne-1.3.0-py2.7.egg/daphne/server.py", line 101, in run
>     websocket_handshake_timeout=self.websocket_handshake_timeout
> TypeError: __init__() got an unexpected keyword argument 'proxy_forwarded_proto_header'
> user@user-OptiPlex-GX620:~/main_folder/amanet$
>

**Comment by andrewgodwin** [comment]
Looks like a version mismatch between channels and daphne - just make sure everything is the latest version.
