### ISSUE TITLE
Low apparent concurrent connection limit

### ISSUE THREAD

**Issue by bartlomieju** [django/daphne#144]
I've been using Daphne in production for a few months now, and it works really great. But lately as we were scaling I started having some troubles with number of connections. 

Stack: I run `nginx` as a reverse proxy that routes all `WebSocket` traffic to Daphne over HTTP. I have defined `upstream daphne` with multiple entries for each of Daphne instances (which are running on different ports, bound to `0.0.0.0`). 

I've seen that clients have trouble connecting WebSocket when Daphne hits ca. 250 open file descriptors (I guess 1 `fd` per connection, so that would suggest 250 connections). System-wide file descriptor limit is not a problem, as it is very high and certainly not hit.

From what I've seen in Channels benchmarks I would suppose Daphne could handle many more connections (especially if it was handling HTTP requests as well). Am I missing something? Maybe we could work on some example configurations and/or tips&tricks for scaling so other people can have easier times doing so?

**Comment by andrewgodwin** [comment]
Daphne/Channels 2 is now released, could you (or someone) re-test and see what things look like now?

**Comment by ploggingdev** [comment]
It looks a lot better now. Not a rigorous load test, but my chat room built using the latest available versions of channels, daphne, channels_redis was able to handle 300+ simultaneous users running on a VM with 1 cpu, 1gb of ram. Cpu usage was around 18% and ram usage was around 60% . 
![screenshot_20181024_010735](https://user-images.githubusercontent.com/23113993/48131863-82430180-e25f-11e8-980e-c94d03e2b244.png)

**Comment by andrewgodwin** [comment]
Yeah, we improved a lot of stuff this year performance-wise, especially in channels-redis. I think I will close this for now, and it can be reopened if some concrete testing or numbers  come through.
