### ISSUE TITLE
Routing errors not being detected properly

### ISSUE THREAD

**Issue by muhammedabad** [django/daphne#145]
I discovered a bug in my WS connection a little while ago which was due to a missing trailing slash in my nginx config.

I had always assumed that everything was working properly, simply because I was seeing a confirmation message in the JS console resulting from the below:

```javascript
 ws.onopen = function() {
    if (ws.readyState == 1) {
     console.log("web socket opened successfully");
  }
};
```

Here's an extract from my settings file:

```python
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "ROUTING": "myapp.settings.channels.channel_routing",
    },
}
```

So here's what I expect to see in the logs if the connection is successful:

```
2017-11-22 12:28:25,875 - DEBUG - worker - Dispatching message on websocket.connect to notifications.consumer.ws_connect

```

But here is what was actually happening:

```
2017-11-22 13:11:03,237 - DEBUG - worker - Dispatching message on websocket.connect to channels.routing.connect_consumer
```

I was under the assumption that since my routing is defined in my settings file, any `websocket.connect` attempt should fail (or raise some warning) if it does not match the one specified in my routing. I'm just concerned that a fallback seems to kick in without any indication.

**Comment by andrewgodwin** [comment]
I'm afraid that in the current design of Channels 1 there is a built-in `websocket.connect` fallback by design for backwards-compatibility reasons. Channels 2 gets to be a breaking change and so will stop this, but until then there's not much I can do, sorry.
