### ISSUE TITLE
onConnect ws_protocol error for websocket connections

### ISSUE THREAD

**Issue by vahava** [django/daphne#149]
app-server-web | 2018-01-04 19:00:56,144 ERROR    Traceback (most recent call last):
app-server-web |   File "/usr/local/lib/python3.6/site-packages/daphne/ws_protocol.py", line 65, in onConnect
app-server-web |     self.client_addr
app-server-web | ValueError: too many values to unpack (expected 1)

I'm trying to make a websocket connection like ws://localhost:8000 on a centos machine.
In docker, I'm starting a daphne instance like thus:
daphne -b 0.0.0.0 -p 8000  --proxy-headers server.asgi:channel_layer &

Running python3, an nginx proxy from a message queue request. I've noticed that if I change the ws_protocol.py on line ~61, it works:
self.client_addr, = parse_x_forwarded_for(
                    self.http_headers,
                    self.main_factory.proxy_forwarded_address_header,
                    self.main_factory.proxy_forwarded_port_header,
                    self.main_factory.proxy_forwarded_proto_header,
                    self.client_addr
)

Changed to (for the sake of a simple hack, I'll just write spaghetti):
x = None
self.client_addr,x = parse_x_forwarded_for(
                    self.http_headers,
                    self.main_factory.proxy_forwarded_address_header,
                    self.main_factory.proxy_forwarded_port_header,
                    self.main_factory.proxy_forwarded_proto_header,
                    self.client_addr
)

It looks like the comma after the self.client_addr is not sufficient in receiving the response. I'm not super familiar with this aspect of python - does anyone know what I'm doing wrong? Is there a flag to address this issue?

**Comment by belongwqz** [comment]
The same problem with me(with version 1.4.1),  no problem with version 1.3.0.

**Comment by andrewgodwin** [comment]
Looks like a bug in the 1.4 series. Please roll back to 1.3 for now while I work out the fix.

**Comment by andrewgodwin** [comment]
Should be fixed in the new 1.4.2 release.
