### ISSUE TITLE
Application instances killed before delivering `websocket.disconnect` message

### ISSUE THREAD

**Issue by bpeschier** [django/daphne#152]
I am testing 2.0 and found my websocket cleanup code was not being called.

In the Twisted `onClose` handling at https://github.com/django/daphne/blob/26fa870540f175eb4046a836abb465ebf1a14612/daphne/ws_protocol.py#L129 `discard_protocol` is called and the application queue future is being shut down. This prevents the `websocket.disconnect` message from being processed.

My guess is: the application queue should shut down after it is completely processed.

It can be reproduced by creating a `WebsocketConsumer` and checking whether `disconnect` is called.

Will look into a PR later in the week if I can re-wrap my head in asyncio; it has been a while :)

**Comment by andrewgodwin** [comment]
Hmm, yes, right now it'll delete the application as soon as the socket finishes closing (it'll give the disconnect handler time to run but likely nowhere near enough).

Of course, if an application isn't cooperating it needs to be killed off anyway once the server knows it hasn't got a connection left. Probably best to wait to discard it until either after a timeout (10 seconds?) or until the server hits its connection limit and needs to reap it for extra space?

**Comment by bpeschier** [comment]
Sounds like we can still remove the protocol (step 1 in `discard_protocol`), but need to leave the application running while it finishes up. In the current design there is no clean way to "wait for the queue to empty", which would mean a check on `Queue.empty` or something fancy with `Queue.task_done/Queue.join`: the application gets `Queue.get` and that's the entire interface :-)

Regardless, there needs to be a timeout for when the application has stopped processing the queue, so that seems like a good step 1.

**Comment by andrewgodwin** [comment]
The way to check if the application has finished is to check if its future is `done`, rather than the queues (which are an implementation detail to get stuff in and out). You can see this implemented in the stateless reference server (used for stuff that doesn't have network sockets behind it), here: https://github.com/django/asgiref/blob/master/asgiref/server.py#L134

I think the best approach is something like the garbage collection loop used there.
