### ISSUE TITLE
Minor inconsistency in specification and implementation of http.request more_body key

### ISSUE THREAD

**Issue by JohnDoee** [django/daphne#157]
The specifications does not specify any default or requirement for the `more_body` key when sending [http.request type](https://github.com/django/asgiref/blob/master/specs/www.rst#request) but it is omitted in [Daphne](https://github.com/django/daphne/blob/db68c43de11014e68c1b79554f2dec2bbccb117a/daphne/http_protocol.py#L157-L158)

I assume it is optional and default False.

**Comment by andrewgodwin** [comment]
You're entirely right - I have updated the spec in 1eba5f69bbdec7df9f03f857a6f9ffc4d2b8f651. Thanks for spotting it!
