### ISSUE TITLE
http timeout after successful websocket connection 

### ISSUE THREAD

**Issue by tsiaGeorge** [django/daphne#159]
When daphne upgrades http_protocol to WebSocket,
http remains open, which causes http timeout and websocket disconnection. 

Please see full output at my pull request. 
[https://github.com/django/daphne/pull/158](https://github.com/django/daphne/pull/158)

**Comment by andrewgodwin** [comment]
Right now we're not sure if this is Channels or Daphne, so it's being tracked over here at the moment: https://github.com/django/channels/issues/746
