### ISSUE TITLE
Support for virtual hosting.

### ISSUE THREAD

**Issue by Lukasa** [django/daphne#16]
Inspired by a chat with @meshy about how to run multiple Django sites using a single channels deployment.

A logical thing for smaller operators who run multiple sites to want to do is to deploy multiple Django sites but to share as much as is possible to do to reduce the number of moving pieces in the system.

Clearly, each worker needs to be different (as they literally run different Python code!), so we cannot reduce the redundancy there, but it would be nice to be able to reduce redundancy at the channel and server layer. Exposing multiple virtual channel layers on top of a single logical channel infrastructure is something that I'm not well-suited to opine about (prefix all the channel names, maybe? I dunno), but doing this at the server layer is super obvious: virtual hosting! Let's talk about this here.

In essence, it would be nice to be able to deploy daphne something like this: `daphne -b 0.0.0.0 -p 8001 google.com:django_project1.asgi:channel_layer1 twistedmatrix.com:django_project2.asgi:channel_layer2`: essentially, to be able to tell Daphne "please serve multiple sites from the same IP/port combination in the same process".

There are some questions about the Twisted support for this in the mainline or whether you'd need custom or third-party code (certainly for TLS-based sites you'd need txsni _for sure_), but it seems like a worthy extension. This would allow you to achieve efficient use of machine resources and reduce redundancy.

Thoughts?

**Comment by meshy** [comment]
In particular, I was hoping to be able to run `www.example.com` and `api.example.com` on the same box, and somehow get them to use different sets of workers (but sharing the same redis DB).

As it is, I'm unsure how to separate them.

**Comment by andrewgodwin** [comment]
So, the Django/channels side of everything supports multiple channel layers, but the idea there was to let you separate concerns - e.g. one tuned for HTTP, one tuned for background tasks, and so on. Making Daphne mount multiple ones wouldn't be too much of a challenge, but it's a decent amount of code rewrite.

My initial natural reaction to this is "oh, do it in nginx", but that might be a waste of resources having to run two Daphnes, and of course once TLS/h2 termination gets into Daphne it's much harder. If we add it into Daphne itself, what does the command-line look like?

The alternative is an "ASGI Middleware" that takes requests off of one backend and moves them to one of a few others based on hostname, but that seems excessive and slow.

**Comment by Lukasa** [comment]
The command-line is a good question. We could do the multiple-colons thing I suggested above, but I don't love it. Any other thoughts?

**Comment by andrewgodwin** [comment]
My other instinctual thought is just separating them out and taking order into account, e.g.:

`daphne -p 8001 --hostname api.example.com --hostname exampleapi.com mybackend:channel_layer --hostname www.example.com --default otherbackend:channel_layer`

And making the last specified one the default if no --default is specified.

**Comment by Lukasa** [comment]
Yup, that could also work.

**Comment by andrewgodwin** [comment]
I'll play around some more tomorrow when I have my full day on Channels stuff. Probably focusing on the local-and-remote channel layer first though.

**Comment by andrewgodwin** [comment]
Closing this as WONTFIX as there's no need to share redis DBs or anything now as channels/daphne 2 runs everything in process.
