### ISSUE TITLE
Daphne Connections Leak in Heroku

### ISSUE THREAD

**Issue by ademidun** [django/daphne#164]
I am running a web application using Django and Django Rest Framework on Heroku with a postgresql and redis datastore. I am on the free postgresql tier which is limited to 20 connections.

This hasn't been an issue in the past, but recently I started using django channels 2.0 and the daphne server (switched my Procfile from gunicorn to daphne similar to [this tutorial](https://blog.heroku.com/in_deep_with_django_channels_the_future_of_real_time_apps_in_django)) and now I have been running into all sort of weird problems.

The most critical is that connections to the database are being left open so as the app runs, the number of connections keep increasing until it reaches 20 and gives me the following error message: Operational Error - 'FATAL too many connections for role "usename"'

**Comment by andrewgodwin** [comment]
This is a known issue, we should get it fixed this week: https://github.com/django/channels/issues/871

**Comment by ademidun** [comment]
Duplicate of #80
