### ISSUE TITLE
Application Monitoring Wrapper Not Available for ASGI

### ISSUE THREAD

**Issue by ademidun** [django/daphne#166]
When trying to add New Relic application monitoring to an application, their [documentation](https://docs.newrelic.com/docs/agents/python-agent/installation-configuration/python-agent-integration) indicates that we should add a WSGI wrapper:

```
import myapp
application = myapp.WSGIHandler()

application = newrelic.agent.WSGIApplicationWrapper(application)
```
Since daphne is using the ASGI protocol, this means there is currently no way to integrate application monitoring with an app.

I'm wondering if there is a way to allow New Relic to receive the  requests from daphne. Allowing users to use New Relic, Datadog and other monitoring services.

**Comment by andrewgodwin** [comment]
It's certainly possible to write one as an ASGI middleware, and the specs are out there, but this is not a problem for Channels to solve internally - either the services themselves or a third party needs to write those wrappers.

**Comment by ademidun** [comment]
Sounds good, sorry for all the issues I've opened. I'm still a novice
developer so I'm still learning the best places to ask questions. Thanks
for the help.

Kind Regards,
Tomiwa Ademidun
http://tomiwa.ca
