### ISSUE TITLE
Support systemd socket activation

### ISSUE THREAD

**Issue by ostcar** [django/daphne#17]
Twisted seems to support systemd socket activation: https://twistedmatrix.com/documents/13.2.0/core/howto/systemd.html

I was not able to understand the twisted documentation or sourcecode. So I could not create a pull request.

I would be nice if daphne would support his, because socket activation is the best way (I know) to start systemd units in parallel.

**Comment by andrewgodwin** [comment]
Maybe we can someday, though the docs you link talk about `twistd`, which is not how Daphne runs.

**Comment by ostcar** [comment]
But if twistd can do it, it should be possible to do it by using the twisted API, right?

**Comment by andrewgodwin** [comment]
It's possible to do with any API, but it requires your top-level CLI code understands how the socket is passed from systemd down to you, which means Daphne would have to incorporate code specifically for that.

**Comment by hawkowl** [comment]
It uses endpoints, so see #10.

**Comment by hawkowl** [comment]
(worth saying that once Daphne supports endpoints, it's actually Twisted that has to worry about this, it's at a different layer that Daphne has to care about :) )

**Comment by mcallistersean** [comment]
This actually now works with the merge of #37 and can be closed.

For reference, I used the following systemd config files to get this working

daphne.socket
```
[Socket]
ListenStream=0.0.0.0:80

[Install]
WantedBy=sockets.target
```

daphne.service
```
[Unit]
Description=Daphne

[Service]
ExecStart=/path/to/daphne \
    -e systemd:domain=INET:index=0 \
    project_name.asgi:channel_layer
NonBlocking=true
WorkingDirectory=...
User=...
Group=...
Restart=always
```

In this example systemd listens on port 80 and starts daphne.service as soon as the first client connects to that port.

**Comment by andrewgodwin** [comment]
Ah, of course that fixed it. Hooray!

**Comment by ostcar** [comment]
Wow, thx!

If you add another

django_worker@.service
```
[Unit]
Description=Django Worker

[Service]
ExecStart=/path/to/manage.py runworker
User=...
Group=...
WorkingDirectoy=...
```

Then you can change the daphne.service like:

```
[Unit]
...
Requires=django_worker@1.service
Requires=django_worker@2.service
Requires=django_worker@3.service
Requires=django_worker@4.service
Requires=django_worker@5.service
...
```

to start 5 workers when daphne starts via socket activation. So no need to start something manual.
