### ISSUE TITLE
static pages get ERROR 404 if daphne port is different from 8000.

### ISSUE THREAD

**Issue by felipemaion** [django/daphne#171]
Hi,
If I run `python manage.py runserver` all my static files are loaded ok.
If I run `daphne multichat.asgi:application --port 8888` server returns error 404 for the static files.

Only if I run `daphne multichat.asgi:application --port 8000` the files (CSS, js, etc) are loaded right.

I am trying to deploy this to Heroku, so, my Procfile is 
`web: daphne multichat.asgi:application --port $PORT --bind 0.0.0.0 -v2`

Is there any configuration I am missing? 
As far as I understood I could "pick" the door without this kind of problems.

**Comment by JohnDoee** [comment]
This looks like #167 

Django / Daphne doesn't serve static files outside debug mode, it might work if they're already cached on your client though.

**Comment by felipemaion** [comment]
Thank you!! Issue #167 helped me out. Whitenoise was the way to go.
