### ISSUE TITLE
WebSocket server shouldn't postpone ping for server side send

### ISSUE THREAD

**Issue by yli-cpr** [django/daphne#172]
The last_data is updated when server sends any data to client. And WebSocket server uses this timestamp to decide if it should send a ping.

This actually defeats the purpose of the ping.

The ping is used to check if the client is still responsive. Server sending data doesn't mean client is good

**Comment by andrewgodwin** [comment]
Good point - have pushed a fix to master.

**Comment by yli-cpr** [comment]
thanks

**Comment by yli-cpr** [comment]
Will this fix be picked up in next 1.x release?

**Comment by andrewgodwin** [comment]
Of course. I'm just waiting to do a release because the next one has to be a minor version bump and have a dependency ripple into Channels.

**Comment by yli-cpr** [comment]
Thanks
