### ISSUE TITLE
Two project in same instance EC2

### ISSUE THREAD

**Issue by oularrea** [django/daphne#174]
I have an EC2 server with redis, when I run two django projects on the same server "environment prod and dev with its virtual independent enviroments" in the dev domain the websocket is not able to join the groups in this environment and in the configuration of channels I have the prefix and everything

You can run two different projects sharing the same daphne server and redis instance

Thank you so much

**Comment by andrewgodwin** [comment]
I'm afraid I can't tell what you are asking for - as you say, you should be able to have two things running on one Redis by setting `prefix`. If you are having problems with development environments, I'm afraid I can't help with that unless you can tell me a specific bug in Daphne or Channels that needs to be fixed.

**Comment by oularrea** [comment]
Hello, description of my problem:

Supervisord config
`[program:Daphne_test]
environment=PATH="/home/ubuntu/enviroments/vendetuslibras_test/bin"
command=/home/ubuntu/enviroments/vendetuslibras_test/bin/daphne -u /home/ubuntu/Projects/vendetuslibras_test/daphne.sock --root-path=/home/ubuntu/Projects/vendetuslibras_test config.asgi.application
directory=/home/ubuntu/Projects/vendetuslibras_test
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/home/ubuntu/logs/vendetuslibras_test_daphne.out.log`

Error log

`File "/home/ubuntu/enviroments/vendetuslibras_test/bin/daphne", line 11, in <module>
    sys.exit(CommandLineInterface.entrypoint())
  File "/home/ubuntu/enviroments/vendetuslibras_test/lib/python3.5/site-packages/daphne/cli.py", line 147, in entrypoint
    cls().run(sys.argv[1:])
  File "/home/ubuntu/enviroments/vendetuslibras_test/lib/python3.5/site-packages/daphne/cli.py", line 177, in run
    application = import_by_path(args.application)
  File "/home/ubuntu/enviroments/vendetuslibras_test/lib/python3.5/site-packages/daphne/utils.py", line 11, in import_by_path
    module_path, object_path = path.split(":", 1)
ValueError: not enough values to unpack (expected 2, got 1)`

I use the las version of daphne and channles and django 2.0.2

Thank you so much
