### ISSUE TITLE
Request.finish called on a request after its connection was lost

### ISSUE THREAD

**Issue by intellineers** [django/daphne#175]
After dockerizing my application everything works as it should, but sometimes I get the above mentioned error message. The error message is actually coming from Twisted, however it tells me that I should use Request.notify. I am not sure if this is a bug or if I use daphne just in a wrong way. I have the feeling that the error message is coming mostly when I getting to a page where I am redirected, however I am unable to reproduce this consistently. 

After instpecting the trace a bit more, this might belong actually to django-channels and not here?

Below the trace:
interface_1  | 2018-02-19 09:21:17,628 ERROR    Exception inside application: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
interface_1  |   File "/usr/local/lib/python3.6/site-packages/channels/http.py", line 191, in __call__
interface_1  |     await self.handle(body)
interface_1  |   File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 108, in __call__
interface_1  |     return await asyncio.wait_for(future, timeout=None)
interface_1  |   File "/usr/local/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
interface_1  |     return (yield from fut)
interface_1  |   File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
interface_1  |     result = self.fn(*self.args, **self.kwargs)
interface_1  |   File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 123, in thread_handler
interface_1  |     return self.func(*args, **kwargs)
interface_1  |   File "/usr/local/lib/python3.6/site-packages/channels/http.py", line 227, in handle
interface_1  |     self.send(response_message)
interface_1  |   File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 62, in __call__
interface_1  |     return call_result.result()
interface_1  |   File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 432, in result
interface_1  |     return self.__get_result()
interface_1  |   File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
interface_1  |     raise self._exception
interface_1  |   File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 76, in main_wrap
interface_1  |     result = await self.awaitable(*args, **kwargs)
interface_1  |   File "/usr/local/lib/python3.6/site-packages/daphne/server.py", line 196, in handle_reply
interface_1  |     protocol.handle_reply(message)
interface_1  |   File "/usr/local/lib/python3.6/site-packages/daphne/http_protocol.py", line 213, in handle_reply
interface_1  |     self.finish()
interface_1  |   File "/usr/local/lib/python3.6/site-packages/daphne/http_protocol.py", line 183, in finish
interface_1  |     http.Request.finish(self)
interface_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/web/http.py", line 992, in finish
interface_1  |     "Request.finish called on a request after its connection was lost; "
interface_1  |   Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
interface_1  | 2018-02-19 09:21:17,629 ERROR    Exception inside application: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
interface_1  |   File "/usr/local/lib/python3.6/site-packages/channels/http.py", line 191, in __call__
interface_1  |     await self.handle(body)
interface_1  |   File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 108, in __call__
interface_1  |     return await asyncio.wait_for(future, timeout=None)
interface_1  |   File "/usr/local/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
interface_1  |     return (yield from fut)
interface_1  |   File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
interface_1  |     result = self.fn(*self.args, **self.kwargs)
interface_1  |   File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 123, in thread_handler
interface_1  |     return self.func(*args, **kwargs)
interface_1  |   File "/usr/local/lib/python3.6/site-packages/channels/http.py", line 227, in handle
interface_1  |     self.send(response_message)
interface_1  |   File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 62, in __call__
interface_1  |     return call_result.result()
interface_1  |   File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 432, in result
interface_1  |     return self.__get_result()
interface_1  |   File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
interface_1  |     raise self._exception
interface_1  |   File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 76, in main_wrap
interface_1  |     result = await self.awaitable(*args, **kwargs)
interface_1  |   File "/usr/local/lib/python3.6/site-packages/daphne/server.py", line 196, in handle_reply
interface_1  |     protocol.handle_reply(message)
interface_1  |   File "/usr/local/lib/python3.6/site-packages/daphne/http_protocol.py", line 213, in handle_reply
interface_1  |     self.finish()
interface_1  |   File "/usr/local/lib/python3.6/site-packages/daphne/http_protocol.py", line 183, in finish
interface_1  |     http.Request.finish(self)
interface_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/web/http.py", line 992, in finish
interface_1  |     "Request.finish called on a request after its connection was lost; "
interface_1  |   Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.

**Comment by andrewgodwin** [comment]
Looks like the socket might be going away between the headers being sent and the rest of the body being sent. Do you have any way of replicating this reliably?

**Comment by ploggingdev** [comment]
Try inspecting the headers of a static file using `curl -I "address". I created an issue in the channels repository https://github.com/django/channels/issues/920 but it looks like it might belong here, so should I close the issue?

**Comment by andrewgodwin** [comment]
That doesn't replicate it for me, it still works fine. Does it fail for certain sizes of static files? What versions of `twisted`, `asgiref` and `daphne` do you have installed?

**Comment by ploggingdev** [comment]
`Twisted==17.9.0`, `asgiref==2.1.6`, `daphne==2.0.3`.

I started the development server using `python manage.py runserver`. The exception is raised for javascript and json files. Html and png responses don't raise any exceptions. Size does not seem to be an issue.

**Comment by andrewgodwin** [comment]
Hm, those are the exact versions I have, and I can't make it fail on any of the admin JS, which is what I had to hand. I'll see if I can construct a more elaborate test case.

**Comment by ploggingdev** [comment]
I just tried replicating this with the [multichat](https://github.com/andrewgodwin/channels-examples/tree/master/multichat) project and when I try `curl -I "http://127.0.0.1:8000/static/js/reconnecting-websocket.min.js"` it raises an exception. Sometimes it does not raise an exception the first time, but it does when I enter the curl command again.

OS used : Ubuntu 16.04

**Comment by andrewgodwin** [comment]
I just did precisely that and hammered it with `curl` and it performed perfectly. This is probably down to the semantics of the underlying network layer at this point, as I'm on an Ubuntu 16.04 userland inside of Windows 10's WSL, so I still use native Windows sockets.

I'll try and make a view that serves its content very slowly so I can cut a client off and see if that does it, but it'll take a bit of time.

**Comment by intellineers** [comment]
Sorry for the late response. I though for some reasons I would get a notification if someone answered me. I do not really have a reliable way on replicating this but so far it only occurred withing docker, however it doesn't really mean that my system does not work as everything continues to work as expected and I just receive a the error message in my terminal. Therefore I am not sure what impact it has after all.

In addition to that, this error occurs when not opening a Websocket Connection, but rather when requesting a normal HTTP Request. 

If you need additional logs from me, please let me know.

**Comment by JohnDoee** [comment]
This error is fixed by https://github.com/django/daphne/commit/de0811f13e551cd826ffd812e1c33db6cd379c8b because you're using the channel variable as proxy for checking if request is finished.

I'd recommend actually checking request.finished as that's what you should do. This'll also help with https://github.com/django/daphne/issues/178

**Comment by groar** [comment]
I've created a minimal example that replicates the issue consistently (I was going to post an issue when I saw someone already did two days ago). However, it only happens to me when using nginx together with `runserver`.

The exception is only triggered when requesting a static file.

--[ Terminal 1:

```
$ mkdir /tmp/channels
$ cd /tmp/channels
$ virtualenv --python /usr/bin/python3 virtual
$ . virtual/bin/activate
$ pip install django channels
$ django-admin startproject testing  
$ vim testing/testing/settings.py  
[add channels to INSTALLED_APPS + ASGI_APPLICATION, SEE BOTTOM]

$ vim testing/testing/routing.py
[EMTPY ROUTES, SEE BOTTOM]

$ vim /etc/nginx/sites-enabled/mysite.conf  
[SEE BOTTOM]

$ cd testing  
$ ./manage.py runserver 0.0.0.0:9000 -v 3 
```

--[ Terminal 2:

```
$ curl 'http://localhost:8080/static/admin/css/fonts.css'
```

(you may need to do it a few times, but in my experience, it does trigger the exception the first or second time)

Result:
```
2018-02-21 10:00:13,199 - ERROR - server - Exception inside application: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
...
...
  File "(...)/virtual/lib/python3.6/site-packages/twisted/web/http.py", line 992, in finish
    "Request.finish called on a request after its connection was lost; "
```

--[ Content of settings.py:

```
...

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'testing',
]

ASGI_APPLICATION = "testing.routing.application"

...
```

--[ Content of routing.py

```
from django.conf.urls import url

from channels.routing import ProtocolTypeRouter

application = ProtocolTypeRouter({})
```

--[ Content of /etc/nginx/sites-enabled/mysite.conf

```
server {
    listen       8080;
    server_name  localhost;

    location / {
          proxy_pass http://localhost:9000/;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Scheme $scheme;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
    }
}
```
