### ISSUE TITLE
Running multiple daphne processes

### ISSUE THREAD

**Issue by ploggingdev** [django/daphne#176]
Gunicorn has an option to specify the number of workers using `--workers`. Is there such an option with daphne as well? If not, any recommendations/guidelines about running multiple daphne processes?

**Comment by andrewgodwin** [comment]
Daphne doesn't have a worker model as it's natively async (gunicorn needs them as WSGI is not). You can set the number of threads available for synchronous calls into Django with `ASGI_THREADS` - it's uncapped by default - but if you want multiple processes you need to use a process manager like `supervisor` or containerisation like `docker` which are built for this.
