### ISSUE TITLE
Exceedingly slow response time for HTTP requests

### ISSUE THREAD

**Issue by michaelhays** [django/daphne#185]
I'm running a very simple (backend-wise) app with Daphne 2.0 as the app server. The app is hosted on Heroku. I recently noticed that HTTP requests on the live webpage are _really_ slow when using Daphne.

I ran some speed tests for Daphne vs. Gunicorn. The web worker run command was the only thing I changed between tests.

My `routing.py` file:

``` python
application = ProtocolTypeRouter({
    'websocket': AuthMiddlewareStack(
        URLRouter([
            url('^chat/stream/$', ChatbotConsumer),
        ]),
    ),
})
```

However, keep in mind that I never triggered the `/chat/stream/` endpoint when running these tests, so requests were all HTTP. As I [understand it](https://channels.readthedocs.io/en/latest/topics/routing.html#protocoltyperouter), leaving `'http'` unrouted defaults to using Django's usual method of handing HTTP requests.

---

For a web worker using `daphne myproject.asgi:application -b 0.0.0.0 -p $PORT`:

![daphne waterfall](https://user-images.githubusercontent.com/6445661/37887487-aa07599e-3087-11e8-9807-da2d98e35e83.png)

For the exact same app, using `gunicorn myproject.wsgi`:

![gunicorn waterfall](https://user-images.githubusercontent.com/6445661/37887493-b689f73a-3087-11e8-84a2-f56efbccb19d.png)

Notice the extreme disparity between the two: 2000 ms vs. 100 ms for small static files. The call to `/app-data` simply loads user-based information using the Django ORM.

---

Some Heroku metrics, tested by clearing the cache and refreshing the page very five minutes. Daphne is on the left and right, Gunicorn in the middle.

![selection_014](https://user-images.githubusercontent.com/6445661/37887598-4c67f162-3088-11e8-81d3-56d7fe732a8c.png)

![selection_015](https://user-images.githubusercontent.com/6445661/37887619-709252b2-3088-11e8-8ee6-a7cc9afa4f1b.png)

![selection_013](https://user-images.githubusercontent.com/6445661/37887657-9ec9df42-3088-11e8-9311-adfd98860384.png)

I couldn't definitively determine if the app was also more likely to have a high Dyno Load when using Daphne, but that seemed to be the case. There's no memory issue; memory usage was slightly lower for Daphne than Gunicorn.

---

Any ideas?

**Comment by andrewgodwin** [comment]
Can you reproduce this on an environment other than Heroku? There's been some weird behaviour reported on there recently for Channels stuff and I don't know exactly what's different about their runtime environment.

**Comment by michaelhays** [comment]
Sure, I'll try it on AWS or GCP with a basic project when I get the chance, hopefully sometime this week.

**Comment by luk156** [comment]
i've the same issue, fro 3 seconds to 10 seconds on a request that do a lot of database query

**Comment by andrewgodwin** [comment]
Are you using `group_send` at all? There's known slowness problems with that right now.

**Comment by d6tdev** [comment]
I'm getting the same running locally Ubuntu 16.04 

```
web: daphne django_combine.asgi:application --port 8000 --bind 0.0.0.0 -v2
worker: celery -A django_combine worker -c 1 --without-gossip --without-mingle --without-heartbeat
worker2: python manage.py runworker channels -v2
```

**Comment by Zarathustra2** [comment]
@andrewgodwin Any Information when group_send will be fixed? Using Daphne, Heroku & Group-Send it takes almost 3-10 secs, depending on the size of my chat, until the message comes through. Without group-send everything works fine.

**Comment by andrewgodwin** [comment]
@Zarathustra2 It should be fixed in the master branch of channels_redis, just waiting to make sure it's stble before I do a release. You can use that version and test it out if you want.

**Comment by michaelhays** [comment]
This seems to be fixed for me! Fast load time for static files on both GCP and Heroku. I think this is ready to be closed.

**Comment by andrewgodwin** [comment]
Great.

**Comment by ploggingdev** [comment]
Are there any known issues with the master branch of channels_redis that uses lua scripts? If not, can we get a release?

**Comment by andrewgodwin** [comment]
There are not - I've just issued a 2.2.0 release.

**Comment by typistX** [comment]
@d6tdev @michaelhays - can you guys kindly share some of your local an Heroku settings? 

I’m expriencing slowness on both when Debug=False
