### ISSUE TITLE
Wrong result from django.url.reverse when using Daphne in production

### ISSUE THREAD

**Issue by morlandi** [django/daphne#186]
I recently started using Daphne to learn django-channels.
To keep configuration as simple as possible, I got rid of gunicorn for the moment, thus using Daphne as WSGI for HTTP. 
I'm using Nginx as reverse-proxy and installed the following:

- Django: 2.0.3
- Python 3.6.3
- channels==2.0.2
- channels-redis==2.1.1

Surprisingly, both HTTP and websocket messages seem to work even with no worker running.

What puzzles me is the behaviour of django.urls.reverse():

```
Testing reverse('admin:auth_group_changelist') ...
Expected result: "/admin/auth/group/"
Actual result: "/home/testproject/testproject/admin/auth/group/"
```

Note that the actual result cointains the root of the Django project, instead of a relative address.
If I follow the link, it just works, but this might be a source of problems should the application logic need to parse the url for any reason.
When I run the same code for local development, using the version of runserver managed by Daphne, I obtain the expected result:

```
Testing reverse('admin:auth_group_changelist') ...
Expected result: "/admin/auth/group/"
Actual result: "/admin/auth/group/"
```

This is the view used to run the test:

```
def testpage(request):
    from django.urls import reverse
    from django.http import HttpResponse

    text = """
    Testing reverse('admin:auth_group_changelist') ...<br />
    Expected result: "/admin/auth/group/"<br />
    Actual result: "%s"<br />
""" % reverse('admin:auth_group_changelist')

    return HttpResponse(text)

```
and this is my nginx config file:

```
server {
    listen 80;
    server_name testproject.brainstorm.it;
    location ~ \.(cgi|fcgi|rb)$  { deny all; }
    location ~ /\.ht             { deny all; }

    location /media {
        alias /home/testproject/public/media;
    }

    location /static {
        alias /home/testproject/public/static;
        access_log   off;
        expires modified 1m;
    }

    location / {
            proxy_pass http://unix://home/testproject/run/daphne.sock;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
    }

    access_log /home/testproject/logs/access.log;
    error_log /home/testproject/logs/error.log;
}

```
Any suggestion is very welcome

**Comment by andrewgodwin** [comment]
I'm afraid I don't know what's happening. I'd check your settings and if you have `SCRIPT_NAME` or similar set anywhere.

**Comment by morlandi** [comment]
Thank you, @andrewgodwin ;
I double checked this with "multichat" sample project.
I forked it to:

https://github.com/morlandi/channels-examples

added the result for reverse() in the page header (file base.html):

`        <div>reverse of 'admin:auth_user_changelist': {% url 'admin:auth_user_changelist' %}</div>`

and just a few customizations to the original settings:

```
STATIC_ROOT = os.path.abspath(os.path.join(BASE_DIR, '..', '..', 'public', 'static'))
DEBUG = False
ALLOWED_HOSTS = ['*']
```

The project has been deployed to:

http://dmultichat.brainstorm.it

and 

http://gmultichat.brainstorm.it

where "g" means "gunicorn" and "d" means "daphne", to show that the problem with reverse() is somehow related to daphne, or, more probably, my configuration for daphne;
here's a screenshot showing the result:

https://github.com/morlandi/channels-examples/blob/master/multichat/deployment/etc/screenshot.png

Nginx config file:

https://github.com/morlandi/channels-examples/blob/master/multichat/deployment/templates/nginx.conf

Supervisor config file:

https://github.com/morlandi/channels-examples/blob/master/multichat/deployment/templates/supervisor.conf

Any suggestion on how to investigate the problem would be much appreciated.
Thank you for your great work on django-channels.

**Comment by andrewgodwin** [comment]
I'm afraid I don't know off the top of my head what might cause it and I am taking a few weeks off from Channels work so I will not be able to help you investigate. I would suggest looking at the properties on the Django `request` object that Django uses to reverse paths and make sure `request.META['SCRIPT_NAME']` is not set strangely.

**Comment by andrewgodwin** [comment]
`SCRIPT_NAME` comes from the Daphne `root_path` setting, which should be empty by default - you can see if it's somehow being overridden by looking for what `root_path` is set to in `request.scope` (which is a Channels-only extension). If that's somehow being set, that's your problem, though I'm not sure how that would happen without you passing it on the command line.

**Comment by morlandi** [comment]
That was it, thank you sir !
Daphne was run via Supervisor, which (my bad !) supplied root_path on the command line.
I guess I grabbed a snippet somewhere for the supervisor config file, and distracted by nginx config details didn't notice it.
Works perfectly now, thank you so much.
