### ISSUE TITLE
Is it really recommended to use daphne with another wsgi application like uwsgi?

### ISSUE THREAD

**Issue by hongmingu** [django/daphne#189]
In django-channels docs, there is some adverting of using another wsgi application [from this](http://channels.readthedocs.io/en/latest/deploying.html#http-and-websocket),

So, I want to ask about difference between daphne and uwsgi.

There is no serious performance difference but just difference like accumulation of experience, users? Isn't it?

Sorry for such abstract question. But because I already read that daphne can do auto-balancing somewhat, this [sentence](http://channels.readthedocs.io/en/latest/deploying.html#http-and-websocket) is making me confused. 

Is it really recommended or It is just one of other options?

**Comment by andrewgodwin** [comment]
It's merely that `uwsgi` is more mature software and so more trusted. Daphne still has occasional bugs and a smaller maintenance team, so if you value low risk over more HTTP features, you can use `uwsgi` to serve the HTTP parts.
