### ISSUE TITLE
Django no shows custom template, 4xx 5xxx

### ISSUE THREAD

**Issue by felipe3dfx** [django/daphne#190]
Django 2.0.4
Channels 2.1.0

Settings:
`DEBUG = False`

If Django raise a server error, it no shown custom template:

![Daphne error](https://s3.amazonaws.com/uploads.hipchat.com/50553/3393916/AsHs2KmTtXuRNv1/Screen%20Shot%202018-04-16%20at%203.04.12%20PM.png)

Daphne service:
```

[Unit]
Description=Daphne Service
After=network.target

[Service]
User=deploy
Group=deploy
WorkingDirectory=/home/deploy/{{ repo_slug }}/
ExecStart=/usr/local/bin/daphne app.asgi:application --unix-socket=/tmp/daphne.sock
Restart=always

[Install]
WantedBy=multi-user.target
```

What I'm I missing here?

**Comment by andrewgodwin** [comment]
It means your error is too fundamental to be caught by Django's error handling system and is instead bubbling up to be caught by Daphne. This would also happen with a normal WSGI server, where you'd see a very plain error page.
