### ISSUE TITLE
ODROID , resolution settings not working

### ISSUE THREAD

**Issue by bebess** [django/daphne#198]
Hi !
i'm on odroid (xu4) version of daphne

the command line 
-fullscreen x-640 y-480

doesn't work at all , i can change to 640x480 or 1024x768 or another resolutions
that dont change anything , i stay with a very very tiny screen (maybe 320x200)

**Comment by andrewgodwin** [comment]
I think you have the wrong thing called Daphne - this is a Python webserver.
