### ISSUE TITLE
ram consumption

### ISSUE THREAD

**Issue by luk156** [django/daphne#201]
Sorry for my english.

the ram consumption of my istances grow over time. 
I've a big query in my code that raise a 504 error on my server,i've to fix this bug but at the same time i see that the memory consumed by daphne process it is not reduced. it increases during query but does not decrease after

**Comment by andrewgodwin** [comment]
Python does not free up memory once it has been allocated; this is just the way the Python VM works. Once you've used memory, it's stuck to the Python process until it exits, but it should be re-used for future large queries.

**Comment by yeungocanh** [comment]
So we have not any resolution for this issue. I must restart server every 3 day because full RAM load.

**Comment by andrewgodwin** [comment]
Well I would need proof that it's daphne and not - as most memory leaks are - your application. If you want to rule out Daphne you can try using `uvicorn` instead as an alternative ASGI server that also works with Channels.
