### ISSUE TITLE
Initialize asyncio reactor with preconfigured ThreadPoolExecutor to control thread counts

### ISSUE THREAD

**Issue by robdoesstuff** [django/daphne#203]
Daphne currently initializes an asyncio reactor with no default executor, so when something like aioredis is used (as it is in redis_channels), a default ThreadPoolExecutor is created on first execute call which has cpu_count * 5 threads as default (which is suboptimal for many deployments).

Consider adding something like the following to daphne's server.py where plain asyncioreactor.install() is being used now:

from asyncio.events import new_event_loop
from concurrent.futures import ThreadPoolExecutor

    event_loop = new_event_loop()
    threadpool = ThreadPoolExecutor(
        max_workers=(
            int(os.environ["ASIO_THREADS"])
            if "ASIO_THREADS" in os.environ
            else None
        )
    )
    event_loop.set_default_executor(threadpool)
    asyncioreactor.install(event_loop)

When testing on OSX, I was able to control the asyncioreactor thread pool size using the ASIO_THREADS env variable with this code.

**Comment by andrewgodwin** [comment]
I have, instead of doing it in Daphne, modified `asgiref` to work from the default executor rather than its own and have `ASGI_THREADS` affect that top-level executor, so that should fix it in a different way - if you want to try the latest commit to the `asgiref` master, that would be great.
