### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'done'

### ISSUE THREAD

**Issue by em1208** [django/daphne#206]
I'm running daphne 2.1.1 under nginx proxy. When I connect to the websocket I get this error:

ERROR 2018-05-24 05:46:01,284 base_events 22 140015681480448 Exception in callback AsyncioSelectorReactor.callLater.<locals>.run() at /usr/local/lib/python3.5/site-packages/twisted/internet/asyncioreactor.py:287
handle: <TimerHandle when=599743.236895389 AsyncioSelectorReactor.callLater.<locals>.run() at /usr/local/lib/python3.5/site-packages/twisted/internet/asyncioreactor.py:287>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.5/site-packages/twisted/internet/asyncioreactor.py", line 290, in run
    f(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/daphne/server.py", line 213, in application_checker
    if not application_instance.done():
AttributeError: 'NoneType' object has no attribute 'done'

Looks like a bug in daphne. Any help please?

**Comment by andrewgodwin** [comment]
I need more information:

- Does this happen every single connection? Or just sometimes?
- What does your routing look like?
- What versions are you running of `daphne`, `channels`, `asgiref`, `channels-redis`, and `twisted`?

**Comment by em1208** [comment]
Hi Andrew, thanks for your quick reply! I'm using:

- asgiref                     2.3.2       
- channels                    2.1.1       
- channels-redis              2.2.1       
- daphne                      2.1.1       
- Twisted                     18.4.0 

This error happens on every connections. I wrote a consumer using AsyncJsonWebsocketConsumer. I wrote a echo consumer using WebsocketConsumer and that works fine.

**Comment by andrewgodwin** [comment]
OK, if it happens on every connection then it's likely a problem with your consumer - sounds like it's not returning itself when it's initiated. Can you post its source code?

**Comment by em1208** [comment]
Hi Andrew, unfortunately I cannot longer reproduce the bug and I haven't touched the consumer code. I just tried to trigger the problem again after the service was running for a while without success. That's weird :sweat_smile:. Anyway, just by looking at the code in https://github.com/django/daphne/blob/c4360fd70aff2907a3b67c97e73abe588d394a30/daphne/server.py#L209-L219
do you think that there can be cases when application_instance is None? Because that's what causing the problem.

**Comment by andrewgodwin** [comment]
I suspect what's happening is that loop is getting to a connection's details before the application has been started. I'll add a not-None check in.
