### ISSUE TITLE
Version 2.1.2 breaks websocket connections with AssertionError

### ISSUE THREAD

**Issue by xolan** [django/daphne#207]
Hi!

The newly released version `2.1.2` breaks my websocket connections with the following error:

```
2018-05-24 16:00:48,563 ERROR    Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/lh8-tools-QNwECfds/lib/python3.6/site-packages/daphne/ws_protocol.py", line 56, in onConnect
    self.client_addr
  File "/root/.local/share/virtualenvs/lh8-tools-QNwECfds/lib/python3.6/site-packages/daphne/utils.py", line 49, in parse_x_forwarded_for
    assert all(isinstance(name, bytes) for name in headers.keys())
AssertionError
```

Would be nice if it told us what was wrong instead of just raising an AssertionError :)

Javascript websocket-client.
Daphne proxied behind nginx or caddy.

Reverting to `2.1.1` fixes the issue.

Related commit: https://github.com/django/daphne/commit/b3c097aabdc477ed7e666a4a0d87250db1b2a9d2

**Comment by xolan** [comment]
I can when I'm back at work tommorow.

**Comment by JohnDoee** [comment]
@andrewgodwin You're not using Twisted Headers for websocket, you're using autobahn headers. They don't seem to provide any such guarantee.

**Comment by andrewgodwin** [comment]
Oh, right, I forgot about that part. I would still like to work out why it's sometimes not bytestrings though, as the ASGI spec guarantees headers as bytes and so I would need to work out what encoding they're being decoded into.

**Comment by JohnDoee** [comment]
I did a quick test on fully updated Ubuntu 16.04 now and when using websocket and the headers aren't bytes. I tested by adding a `print(self.http_headers)` to this line: https://github.com/django/daphne/blob/master/daphne/ws_protocol.py#L50

Can you give a scenario where you're actually seeing byte headers when using websocket ? I read a bit more of the autobahn code and I see no indications of it ever being bytes.

**Comment by andrewgodwin** [comment]
On my Ubuntu 18.04/Python 3.5.2 system it's always bytes. Strange. I'll dig into the code next week.

**Comment by JohnDoee** [comment]
What version of autobahn ?

**Comment by andrewgodwin** [comment]
Just tried both 17.9 and 18.4, both still pass bytes.

**Comment by JohnDoee** [comment]
The bug is probably fixed by changing https://github.com/django/daphne/blob/master/daphne/ws_protocol.py#L53 to `self.clean_headers`

**Comment by andrewgodwin** [comment]
Agreed, that set of headers is already guaranteed bytes - I just made that change. I wonder why the `http_headers` one varies in type though, that seems... not great.

If someone could confirm that the change I just made works for them, that would be lovely.

**Comment by xolan** [comment]
@andrewgodwin here are some os/package details:

### OS

```
$ cat /etc/issue
Arch Linux \r (\l)

$ uname -a
Linux xolan-workbook 4.14.41-1-lts #1 SMP Wed May 16 15:10:39 CEST 2018 x86_64 GNU/Linux
```

### Python

```
$ pipenv run python -V
Python 3.6.4

$ pipenv run pip freeze

<snipped to mostly relevant packages>
asgiref==2.3.0
autobahn==18.5.1
channels==2.1.1
channels-redis==2.1.1
cryptography==2.2.2
daphne==2.1.1  # (2.1.2 on error above)
Django==2.0.5
djangorestframework==3.8.2
msgpack==0.5.6
requests==2.18.4
requests-oauthlib==0.8.0
simplejson==3.15.0
tornado==5.0.2
Twisted==18.4.0
txaio==2.10.0
```

### How it's ran

_Daphne_

Via `supervisord`

```
---snip---
[program:django-daphne]
process_name=%(program_name)s-%(process_num)02d
directory=./app
command=/bin/bash -c "pipenv run daphne -b 0.0.0.0 -p 8000 --proxy-headers app.asgi:application "
numprocs=1
autostart=true
autorestart=true
priority=2
stopasgroup=true
stopsignal=QUIT
---snip---
```

_Complete flow_

```
Internets
-> Host
    -> Docker
      -> proxy container (caddy or nginx), caddy uses the  _websocket_ and _transparent_ presets
      -> django container
      -> postgres/redis/rabbitmq containers
```

Javascript client connects over Websocket Secure / `wss`.

Only the proxy is directly exposed.

In production, it's on a Ubuntu 18.04 host. I do have the same error on arch using the same deployment method though.

Do you need anything else?

**Comment by andrewgodwin** [comment]
@xolan Could you try daphne from the master git branch and see if that fixes it?

**Comment by xolan** [comment]
Entered container and installed `@master` and restarted supervisord processes.

Getting this now:

```
2018-05-25 15:48:29,631 ERROR    Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/lh8-tools-QNwECfds/lib/python3.6/site-packages/daphne/ws_protocol.py", line 56, in onConnect
    self.client_addr
  File "/root/.local/share/virtualenvs/lh8-tools-QNwECfds/lib/python3.6/site-packages/daphne/utils.py", line 46, in parse_x_forwarded_for
    headers = {name.lower(): values for name, values in headers.items()}
AttributeError: 'list' object has no attribute 'items'
```

**Comment by xolan** [comment]
Logging the headers yields the following:

```
# utils.py
46: ...
47: logger.info(pprint.pformat(headers))
48: # Lowercase all header names in the dict
49: headers = {name.lower(): values for name, values in headers.items()}
50: ...

---

[(b'host', b'<snip>'),
 (b'user-agent',
  b'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) C'
  b'hrome/66.0.3359.181 Safari/537.36'),
 (b'accept-encoding', b'gzip, deflate, br'),
 (b'accept-language', b'en-US,en;q=0.9'),
 (b'cache-control', b'no-cache'),
 (b'connection', b'Upgrade'),
 (b'origin', b'<snip>'),
 (b'pragma', b'no-cache'),
 (b'sec-websocket-extensions', b'permessage-deflate; client_max_window_bits'),
 (b'sec-websocket-key', b'FgpaSlzpKdUPh29dLprt1g=='),
 (b'sec-websocket-version', b'13'),
 (b'upgrade', b'websocket'),
 (b'x-forwarded-for', b'<snip>'),
 (b'x-forwarded-proto', b'https'),
 (b'x-real-ip', b'<snip>')]
```

**Comment by xolan** [comment]
@JohnDoee That seems to do the trick :)

**Comment by andrewgodwin** [comment]
Whoops, my bad, we should probably have a test for that. I'll fix it and add one.

**Comment by andrewgodwin** [comment]
OK, should be fixed now and there's a test to make sure it stays that way.
