### ISSUE TITLE
Any chance of having a base init script to manage lifecycle via systemd/upstart/etc?

### ISSUE THREAD

**Issue by greysondn** [django/daphne#210]
Wow, what a mouthful.

I can't track everything that daphne must be dependent on already being loaded, but it seems like there is no reason that basic init recipes can't be given. And it's precisely because I can't track all of that for a django-channels project that, you know, this is put here.

**Comment by andrewgodwin** [comment]
I'm not sure why you would need an init script defined from us? Daphne needs no setup or preconfiguration of files and takes all its arguments via a command line, so it should drop directly into any standard init script template for a similar webserver (e.g. gunicorn).

On top of that, having to write separate ones for three or four different systems is not something we can commit to maintaining write now, so I'm afraid you'll have to do it yourself.

**Comment by greysondn** [comment]
The whole premise of even having a boot manager is that things can be sensitive to ordering when loading. Daphne wasn't (isn't) playing nice with templates for init scripts that I've seen, and init scripts aren't exactly plain english by way of comparison to most scripts one typically reads and writes. 

If you'd like, once the project I'm on matures past being okay on the development server (`./manage.py runserver` or whatever, I'm not logged into my server right now), I can at least dump my init script and the problems I have.

---

Follow-through

It shouldn't seem undocumented to run daphne:
* under the standard daemon management in Ubuntu LTS (upstart? systemd? Either way)
* behind apache2, via proxying through
* fluidly alongside other internet applications, with or without isolation.

Recipes for these seem wise. If you would like, I am also open to pushing whatever I've got/end up with upstream to you as third-party resources... if, and only if, I get it running well enough to feel I'm not destabilizing other people just by offering that.

**Comment by andrewgodwin** [comment]
Feel free to post them up here or somewhere else for people to refer to, but we won't be able to have them in the main repo because of the extra maintenance overhead, unless we somehow end up with more volunteer help.
