### ISSUE TITLE
how to monitor daphne using nagios or similar tools?

### ISSUE THREAD

**Issue by Henner** [django/daphne#211]
what do I have to monitor an how would I do it? Should I monitor all protocols? Using the default check_http does not work. it returns:
Invalid HTTP response received from host on port 443: HTTP/1.1 400 WebSocket connection denied - Hixie76 protocol not supported.

**Comment by andrewgodwin** [comment]
Sounds like a problem with Nagios' HTTP check - Daphne is a normal webserver, just send it a valid HTTP or (modern) WebSocket response and it'll respond. Looks like the check you're using is using an old, pre-specification websocket standard.
