### ISSUE TITLE
Add nginx example config

### ISSUE THREAD

**Issue by kamilgregorczyk** [django/daphne#212]
Hi, could you maybe provide a nginx config (maybe even for http 2) which could be used? 
Many people use nginx as a reverse proxy for static files and for gunicorn/uwsgi proxy to django

**Comment by andrewgodwin** [comment]
I'm afraid I can't provide nginx configs that would work in every case - most of the things that need to be configured vary substantially by deploy. I suggest you look around for people who have examples of nginx configs for any WebSocket server, as they all tend to be similar (Daphne needs nothing more than any other server in other languages apart from being set as the reverse proxy target)

**Comment by kamilgregorczyk** [comment]
@andrewgodwin Thanks, unfortunately nginx doesn't support http2 proxy :( https://serverfault.com/questions/765258/use-http-2-0-between-nginx-reverse-proxy-and-backend-webserver

Do you maybe know a reverse proxy that supports it?
Or am I doing something wrong?

**Comment by andrewgodwin** [comment]
Ah, that's unfortunate. I don't know of an alternative reverse proxy off the top of my head, but the benefits of HTTP/2 are mostly between your servers and the client, so it's not the worst to have HTTP/1.1 between nginx and Daphne.

**Comment by kamilgregorczyk** [comment]
I'm wondering, will there be any benefits for using it between clients and
nginx ?

pon., 2 lip 2018, 00:33 użytkownik Andrew Godwin <notifications@github.com>
napisał:

**Comment by andrewgodwin** [comment]
Yes, you get much better latency if there are lots of resources due to the pipelining. Not something I can explain quickly here, but plenty of writeups elsewhere!
