### ISSUE TITLE
Application instances killed before delivering `websocket.disconnect` message "in case of an exception"

### ISSUE THREAD

**Issue by youshn** [django/daphne#215]
```
channels==2.1.2
channels-redis==2.1.1
daphne==2.2.0
Django==2.0.7
```

is it possible that #152 is still not fixed in case of an exception in my app

**Comment by andrewgodwin** [comment]
I mean it's possible, but you need to give some more information - how do you know they're killed before they get the message? And are you sure you don't have another message handler blocking your app receiving the disconnect (i.e. when you receive something that goes and does a long task and doesn't let your app go fetch the next message)?

**Comment by youshn** [comment]
I just created the chat example, added a print in disconnect and raised an exception in receive

```
2018-07-13 01:26:50,969 - ERROR - server - Exception inside application:
  File "c:\users\youshn\appdata\local\programs\python\python35\Lib\asyncio\tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "C:\test_channels\env\lib\site-packages\channels\sessions.py", line 175, in __call__
    return await self.inner(receive, self.send)
  File "C:\test_channels\env\lib\site-packages\channels\middleware.py", line 41, in coroutine_call
    await inner_instance(receive, send)
  File "C:\test_channels\env\lib\site-packages\channels\consumer.py", line 54, in __call__
    await await_many_dispatch([receive, self.channel_receive], self.dispatch)
  File "C:\test_channels\env\lib\site-packages\channels\utils.py", line 50, in await_many_dispatch
    await dispatch(result)
  File "C:\test_channels\env\lib\site-packages\channels\consumer.py", line 67, in dispatch
    await handler(message)
  File "C:\test_channels\env\lib\site-packages\channels\generic\websocket.py", line 195, in websocket_receive
    await self.receive(text_data=message["text"])
  File "C:\test_channels\mysite\chat\consumers.py", line 36, in receive
    raise ValueError

[2018/07/13 01:26:50] WebSocket DISCONNECT /ws/chat/lobby/ [127.0.0.1:59003]

```
but still can't see the print, hopefully I am not missing something obvious

**Comment by youshn** [comment]
The code is definitely not being executed but no surprise here as the application instance is being directly deleted after `handle_exception` is called where `websocket.disconnect` message is inserted to the queue 
[https://github.com/django/daphne/blob/master/daphne/server.py#L252](url)

The check `application_instance.done()` was true but not anymore after line 251

**Comment by andrewgodwin** [comment]
Well all of that only executes if the application instance's coroutine has completely exited, which means that some code must have raised an exception (it normally won't exit until after it gets the `disconnect` message and handles it)

**Comment by youshn** [comment]
That's exactly the issue "in case of an exception"
I'm sorry if I was not clear enough but I mentioned that in both my comments but not the title

**Comment by andrewgodwin** [comment]
Oh, my apologies, I did not properly read that part of the title. This is the intended behaviour - if your application raises an error it is killed immediately and doesn't get a chance to handle any more messages. If you want to handle things in a less dramatic way, you'll need to add error handling to the methods where the error might happen.

(We have to do this because if an error gets up to the server the coroutine has exited, and we'd have to make a new instance of the application to handle any more messages, which would have different things on `self` anyway)
