### ISSUE TITLE
Nginx Config

### ISSUE THREAD

**Issue by Pinaz9** [django/daphne#216]
I'm trying to define a deployment method for a Django Channels project. Right now, I'm very hung up on how to configure Nginx as a proxy for Daphne. I understand how to route to a unix socket using the `-u` option on Daphne. (For now, until I choose the location of the socket, I'm using TCP.) I understand how to configure static files. What's puzzling me is how to send all non-media requests to Daphne. 

I have not been able to find any tutorials or example configuration on how to do this with Daphne. I can do it with uwsgi, even if I don't quite understand what I'm doing.

My ultimate goal is to provide the project files and a no-knowledge-assumption tutorial on how to deploy the project to a Raspberry Pi. 

I would also like (but do not require) details about what each line in the configuration is doing. This will allow me to round out my understanding of the stack and be able to solve some problems on my own.

**Comment by andrewgodwin** [comment]
Daphne is a pretty normal webserver, so any configuration example for nginx that routes to a backend webserver in this way will work - I suggest you look around for one that works for a similar server (like gunicorn). Unfortunately, providing this sort of thing as an example is not something we have the people or time for at the moment, so I'm afraid I can't do it here.

**Comment by Pinaz9** [comment]
I would be more than happy to write and share the config here. If I do come up with a configuration, I'll reopen the issue and have you take a look. If it passes muster, you'll have my permission to use it in the docs.
