### ISSUE TITLE
Daphne servers urlpatterns but does not routing

### ISSUE THREAD

**Issue by adszzxc** [django/daphne#217]
- Ubuntu 16.04
- Channels 2.1.2
- Daphne 2.2.0
- Twisted 18.4.0
- Django 2.0.7
- Python 3.5.2
It's run on remote Ubuntu VPS. What happens is that it serves `urlpatterns` urls just fine but it does not serve what is in `routing.py`. This was not an issue when running by manage.py, but now it's backed up by Nginx via a socket. When I want to connect to a `ws://`, log throws:
```
Jul 16 02:19:04 isailor daphne[12445]: Not Found: /ws/usercode/e1cfb86161/236b6553fd4b215846e204dfed597f5abaa56147/
Jul 16 02:19:04 isailor daphne[12445]: 2018-07-16 00:19:04,223 WARNING  Not Found /ws/usercode/e1cfb86161/236b6553fd4b215846e204dfed597f5abaa56147/
```
My `routing.py` looks like this:
```
application = ProtocolTypeRouter({
    "websocket":TokenAuthMiddlewareStack(
        URLRouter([
            path("ws/usercode/<str:usercode>/<str:authtoken>/", ChatConsumer),
            ]),
        ),
    })
```
Rest is configured according to Channels deploying docs.

**Comment by andrewgodwin** [comment]
The fact it doesn't work behind Nginx suggests that your Nginx is not actually proxying WebSockets, and instead is turning the WebSocket request into a HTTP request, which Django then doesn't know what it should do with. You should look into configuring your Nginx and any other proxies so they correctly pass through WebSocket and HTTP/1.1 Upgrade requests.
