### ISSUE TITLE
No module named 'daphne.cli'

### ISSUE THREAD

**Issue by RealLau** [django/daphne#220]
I encountered a problem with version 2.2.1 as below:

![image](https://user-images.githubusercontent.com/16678624/43136235-ac2469fe-8f7a-11e8-8cd8-7fe69b329c41.png)

I'm sure I've installed daphne version 2.2.1:
![image](https://user-images.githubusercontent.com/16678624/43136337-f7d42c0e-8f7a-11e8-8c91-567aae07e805.png)

OS: CentOS 7

BUT, when I clone this Repository and install it with 'python3 setup.py install' it works correctly.

Please have a check on daphne 2.2.1 integration with channels.

**Comment by andrewgodwin** [comment]
I just installed and it works perfectly fine - you should make sure your Python settings are correct, especially path wise, as you may have got the wrong python3 install or something.
