### ISSUE TITLE
Couldn't connect daphne with nginx using proxy pass

### ISSUE THREAD

**Issue by ajithsayonetech** [django/daphne#225]
I couldn't use the Nginx proxy pass to access Daphne server for my Django tenant schema architecture, since I use host names to identify my tenant and that is getting altered when I use proxy pass. Is there any alternative way such that I can access web socket requests through Daphne without losing request host name.

**Comment by andrewgodwin** [comment]
Sorry, but we can't help out with general support requests here - the issue tracker is for reproduceable bugs and
concrete feature requests only! Please see our support documentation (http://channels.readthedocs.io/en/latest/support.html)
for more information about where you can get general help.
