### ISSUE TITLE
Improve compatibility with other ASGI server implementations

### ISSUE THREAD

**Issue by almarklein** [django/daphne#228]
Hi! I love ASGI and how it cleanly separates server implementations from frameworks. But I am a bit disappointed that each server implementation has to be called in a slightly different way. I wonder if we can do better. I explored this a idea a bit [here](https://github.com/erm/asgi-examples/issues/2). In summary, it would be very hard and unnecessary to align things all the way; it would already be awesome if we could do:

```
$ daphne --bind 127.0.0.1:80 --log-level info mymodule:myapp
$ uvicorn --bind 127.0.0.1:80 --log-level info mymodule:myapp
$ hypercorn --bind 127.0.0.1:80 --log-level info mymodule:myapp
$ server-something ... you get the idea
```

And also:
```py
from unicorn import run  # replace "unicorn" with "daphne" etc.
run(myapp, bind='127.0.0.1:80', log_level='info', **more_server_specifics)
```

Each server implementation would need just a bit of work to make this happen. For daphne:
* The `--bind` argument to also include the port number, and maybe `fd:` and `unix:` style strings.
* A `run()` function that sits in between [`CommandLineInterface.run()`](https://github.com/django/daphne/blob/master/daphne/cli.py#L143) and [`Server.__init__`](https://github.com/django/daphne/blob/master/daphne/server.py#L37).
* Maybe a `log_level` arg as an "alias" for `verbosity`.

I'd be happy to do some work on this. What do you think?

**Comment by andrewgodwin** [comment]
While I agree it would be nice, I just don't think this is a level of similarity that we can effectively enforce - servers are all going to have different calling styles, and trying to make it all the same is just going to make everyone unhappy. Some implementations will probably not even be command-line applications.

WSGI never specified this, and it's not something I think makes sense to bring into ASGI either; it didn't make things too dissimilar for WSGI and it let things evolve over time. I think a spec should be as minimal as possible, basically.

Given that, I'm going to close this for now - if you want to discuss it further, it's probably something to bring up on the `asgiref` repo instead as that's where spec discussions happen.

**Comment by almarklein** [comment]
Thanks for the quick reply @andrewgodwin.

I agree that it would be a bad idea to make this part of the ASGI spec. My suggestion is merely to have an informal agreement on how the server can be started, by using the same form of the `--bind` arg, and perhaps `log_level`.

E.g. gunicorn and hypercorn allow `--bind host:port`, uvicorn does `--host host --port port`, and daphne `--bind host --port port`. Aligning this would be easy and a big win imo.
