### ISSUE TITLE
Implicit encoding of headers

### ISSUE THREAD

**Issue by imbolc** [django/daphne#229]
Just swapped daphne with uvicorn for my django app and found some errors related to not encoded headers I was sending. Prove me if I'm wrong, but shouldn't daphne reject not encoded strings accordingly to ASGI standard? Here's an example which will be served by daphne but not by uvicorn (notice decoded heareds there):

```python
class App():
    def __init__(self, scope):
        self.scope = scope

    async def __call__(self, receive, send):
        await send({
            'type': 'http.response.start',
            'status': 200,
            'headers': [
                ['content-type', 'text/plain'],
            ]
        })
        await send({
            'type': 'http.response.body',
            'body': b'Hello, world!',
        })
```

**Comment by andrewgodwin** [comment]
Do you mean implicit _en_coding of headers? You're right that Daphne should not accept non-bytestring headers.

**Comment by imbolc** [comment]
Yep, sorry for the typo, should I provide a PR?

**Comment by andrewgodwin** [comment]
That would be great if you could. Just do a typecheck on incoming headers and bubble an error up through `send()` if they're not bytestrings. I think the error machinery should allow you do to that in the protocol handling code and let it bubble all the way back out, but it's worth checking it does with a test.

**Comment by imbolc** [comment]
Done
