### ISSUE TITLE
When using --fd 0, daphne still listen on 127.0.0.1:8000

### ISSUE THREAD

**Issue by sprat** [django/daphne#234]
When you pass `--fd 0` on the command line, daphne still listens on `127.0.0.1:8000`. It's is due to a bad test on `args.file_descriptor` in `CommandLineInterface.run` method when providing default host and port.

**Comment by sprat** [comment]
A workaround before it is fixed: use `--endpoint fd:fileno=0` instead of `--fd 0`

**Comment by pbxue** [comment]
如何使用daphne的FCGI-PROGAM启动多个https进程？ 配置改怎么写
