### ISSUE TITLE
Add way to pass custom options to WebSocketServerFactory

### ISSUE THREAD

**Issue by cbergmiller** [django/daphne#236]
Currently there is no way to pass custom options to `WebSocketServerFactory` (autobahn).
In my case i want to set a `perMessageCompressionAccept` to enable a compression extension.
Is this a feature that would be considered useful for other users?
If so, should this be added as an CLI argument?
I could try to work on an a feature branch if there is a chance for merging.

**Comment by andrewgodwin** [comment]
I'm afraid I'd be unlikely to take it as a command-line option, as it's going to be a feature very few people use. What I would be willing to take is a way to make Daphne subclassable or extensible easily so that factory can be overridden in a custom version.
