### ISSUE TITLE
daphne cannot support on python3.4

### ISSUE THREAD

**Issue by dazhi509** [django/daphne#238]
i try to run my project in enviroment ```python3.4,  channels 2.0.2, daphne 2.2.2```, but error such as: ```async def main_wrap(self, args, kwargs, call_result):  SyntaxError: invalid syntax```,  is there a daphne version that support python3.4 ?

**Comment by andrewgodwin** [comment]
Nope, Daphne needs Python 3.5 or higher. Sorry!
