### ISSUE TITLE
daphne running bug?

### ISSUE THREAD

**Issue by ixser** [django/daphne#241]
I found a bug while develop daphne, the case is: if i set one more works in supervisor, my servermachine CPU useing up to very highly rate, with time going by, even to 100%, what a surprise！here is the screen and my supervisor settings:

![image](https://user-images.githubusercontent.com/33649388/50269499-55daf180-0469-11e9-87df-d3010ccd7712.png)

![image](https://user-images.githubusercontent.com/33649388/50269717-24aef100-046a-11e9-821b-2912cb8e8675.png)

**Comment by andrewgodwin** [comment]
You can't have more than one process listening on the same port - that's why it's failing. Each Daphne instance needs a port to itself.
