### ISSUE TITLE
Server.websocket_handshake_timeout is ignored in CLI

### ISSUE THREAD

**Issue by snb2013** [django/daphne#242]
I cannot set handshake timeout when using daphne CLI. websocket_connect_timeout is not useful, connection breaks after 5 seconds. I try to emulate 300 users and 5 seconds timeout is too small.
I want to have option websocket_handshake_timeout in CLI.

**Comment by andrewgodwin** [comment]
`--websocket_connect_timeout` was meant to be for this, it seems it got disconnected at some point. I have re-linked it in 699f9dd4cb0d27899c801bd3bb8d75642b95703a.

**Comment by snb2013** [comment]
Thanks a lot!
