### ISSUE TITLE
daphne + supervisor : strange behavior

### ISSUE THREAD

**Issue by tboulogne** [django/daphne#249]
Hello,

I follow https://channels.readthedocs.io/en/latest/deploying.html#example-setups and i get a strange behavior if numprocs > 1.

I get ony few messages (around one on three). If i set numprocs to 1, i get all messages.

Any idea on what happend (bug on running daphne in supervisor) ?

Thanks for help.

regards

OS: ubuntu 18.04
supervisor: 3.3.1
channels: 2.1.5
event stream: latest

**Comment by carltongibson** [comment]
Sorry. There's really not enough to go on here. It's not something we realistically have the bandwidth to help you with on the repo unless you can pin it down to a specific fault in Daphne. 

Have a look at https://channels.readthedocs.io/en/latest/support.html for support channels. Good luck!
