### ISSUE TITLE
No module named 'asgiref.compatibility'

### ISSUE THREAD

**Issue by Catastropha** [django/daphne#256]
ModuleNotFoundError: No module named 'asgiref.compatibility'

After the last realease. What should be done?

**Comment by neatsoft** [comment]
Same here:

`pip install channels`:

    daphne 2.3.0 has requirement asgiref~=3.0, but you'll have asgiref 2.3.2 which is incompatible.

`daphne -b 0.0.0.0 -p 8000 config.asgi:application`:

    Traceback (most recent call last):
      File "/usr/local/bin/daphne", line 6, in <module>
        from daphne.cli import CommandLineInterface
      File "/usr/local/lib/python3.7/site-packages/daphne/cli.py", line 7, in <module>
        from asgiref.compatibility import is_double_callable
    ModuleNotFoundError: No module named 'asgiref.compatibility'


Try to use `pip install channels daphne==2.2.5` as a temporary solution

**Comment by erseco** [comment]
Same here

**Comment by alternativshik** [comment]
Same issue for me

**Comment by carltongibson** [comment]
Matching updates for Channels and channels redis are coming this weekend. You can update `asgiref` (it is compatible, despite setup.py leading to a complaint...)

**Comment by carltongibson** [comment]
OK, all packages are updated and look like they're installing without the warnings. I'll close this. 

Please open a new issue if anything else comes up.
