### ISSUE TITLE
SSL not support CertificateChain

### ISSUE THREAD

**Issue by HoangJerry** [django/daphne#265]
Hello there,

I want to run ssl on daphane, and I ran:
daphne -e ssl:443:privateKey=key.pem:certKey=crt.pem django_project.asgi:application

But on godaddy I got the chain certificate and I dont know how the daphne  run it I guess some thing like this?
daphne -e ssl:443:privateKey=key.pem:certKey=crt.pem:chainKey:chancrt.pem django_project.asgi:application
But it's not true.

I got this issue when I scan. Correctly, chrome is work well, however some browser on mobile cannot load my page
![image](https://user-images.githubusercontent.com/27281406/59238249-6d7c8100-8c27-11e9-9f25-172509d0cad2.png)

Thank for your help

**Comment by carltongibson** [comment]
Grrr. You'll need to follow the GoDaddy instructions. (Looks like the error there gives you a link.) 

In general, you'll need to create a file that contains the cert they gave you plus the intermediate certs, in the right order, and use that. 

Not something we can help you with ref Daphne I'm afraid.

**Comment by ArthurNRL** [comment]
For the future people of the earth, I've manage to make it work using godaddy's bundle file, this is the command I'm using:
daphne -e ssl:443:privateKey=key.pem:certKey=cert.pem:extraCertChain=bundle.pem -b 0.0.0.0 -p 80 project.asgi:application
