### ISSUE TITLE
Implement raw_path

### ISSUE THREAD

**Issue by simonw** [django/daphne#267]
Assuming https://github.com/django/asgiref/pull/92 is merged into ASGI (see also https://github.com/django/asgiref/issues/87) Daphne should support the `raw_path` scope key for both HTTP and websocket.

**Comment by simonw** [comment]
I'm happy to file a pull request for this. I've had a little bit of trouble figuring out where the test should go.

Currently the `"path"` key is tested for both websockets and HTTP by calls to this method:

https://github.com/django/daphne/blob/a3494215cf8e2f62d1f4df988cb8a9d16c18fe3d/tests/http_base.py#L250-L257

This doesn't feel quite right for raw_path. We need to test that if the path sent by the client is `/foo%2Fbar` then the `path` scope key is `/foo/bar` but the `raw_key` scope key is b`/foo%2Fbar`.

I think the `assert_valid_path()` method should probably be removed entirely in favour of assertions against both `path` and `raw_path` directly in these two locations:

https://github.com/django/daphne/blob/a3494215cf8e2f62d1f4df988cb8a9d16c18fe3d/tests/test_http_request.py#L43

and

https://github.com/django/daphne/blob/a3494215cf8e2f62d1f4df988cb8a9d16c18fe3d/tests/test_websocket.py#L34

Also, should we continue to rely on hypothesis to cover this particular case or is it worth adding an explicit assertion for the `/foo%2Fbar` case?

**Comment by carltongibson** [comment]
> ...in favour of assertions against both path and raw_path directly in these two locations. 

Yes, exactly, makes sense. `raw_path` becomes part of each protocol, rather than the core handling. 

> ...should we continue to rely on hypothesis to cover this particular case... 

Errr... 🙂 Yep, OK. An explicit assertion seems fine.

**Comment by simonw** [comment]
https://github.com/django/asgiref/pull/92 has been merged!

**Comment by carltongibson** [comment]
Super. Does that mean I’m allowed to act all impatient about this pull request? 🙂

**Comment by simonw** [comment]
https://github.com/django/daphne/pull/268
