### ISSUE TITLE
websocket reject and disconnect connection with vue.js 

### ISSUE THREAD

**Issue by sabuhish** [django/daphne#274]
Hi there!

our team having issue on connection to websocket via Vue.js app.
configuration of channels applied as mentioned on docs. I am using asigiref async_to_sync function to send data to channel_layer.
everything works fine on default browser. When Vue app tries to connect where attemption get rejected. it Actually disconnects from websocket, what could be the problem, have faced this problem before?
Below attaching the codes and pictures:

consumer.py:
https://pastebin.com/dxrCy4YX

vue.js:
https://pastebin.com/SKA4Y3hm
<img width="1440" alt="Screen Shot 2019-07-19 at 11 27 37 AM" src="https://user-images.githubusercontent.com/46589585/61542837-64b37200-aa53-11e9-80a3-8d4110bb4d73.png">
<img width="743" alt="Screen Shot 2019-07-19 at 11 28 12 AM" src="https://user-images.githubusercontent.com/46589585/61542839-64b37200-aa53-11e9-8e60-6b4b28df222a.png">
<img width="555" alt="Screen Shot 2019-07-19 at 11 28 47 AM" src="https://user-images.githubusercontent.com/46589585/61542841-64b37200-aa53-11e9-9b76-1405a6c3d4ba.png">
<img width="1217" alt="Screen Shot 2019-07-19 at 11 30 12 AM" src="https://user-images.githubusercontent.com/46589585/61542842-654c0880-aa53-11e9-8529-8567b6f207c5.png">

**Comment by BillSchumacher** [comment]
I'm using  "vue-native-websocket": "^2.0.13", with no issues. SocketIO is not compatible with websockets.
