### ISSUE TITLE
Unclear if buffering requests is required or not

### ISSUE THREAD

**Issue by WhyNotHugo** [django/daphne#277]
I've been looking at the documentation, and it's not clear if a reverse proxy that does request buffering is required when using daphne (I'm coming over from using gunicorn).

The documentation example uses `nginx`+daphne, but I'm not 100% sure if this is because request buffering is required or not (since it's not explain anywhere).

Would daphne be fine directly exposed to the internet, or would I require having a reverse proxy in front of it to buffer slow clients? Can we add a brief mention of this in the docs?

**Comment by carltongibson** [comment]
> Would daphne be fine directly exposed to the internet?

Good question. More or less it would reduce to Would Twisted be fine directly exposed to the internet?

I can't see that I'd ever really expose an application server without something like nginx, or HAProxy in front. But that's not a "can I?"...

**Comment by WhyNotHugo** [comment]
Right, maybe the exact doubt here is "Does daphne require a _buffering_ reverse proxy in-front of it"?

I currently have ELB->HAProxy->Gunicorn, and I'm wondering if the HAProxy is still required in order to avoid slow connections making daphne stagnate (or it that's not a potential problem).

**Comment by carltongibson** [comment]
_Daphne_ itself does nothing (sensible or not) here. The question is what does Twisted do? (I don't know enough to answer that I'm afraid.)

**Comment by WhyNotHugo** [comment]
That's pretty clear. Thanks for your reply and your time :)
I'll try and figure out what Twisted's situation is.

**Comment by carltongibson** [comment]
OK, I'll close this as it is. If you come to a conclusion **very happy** to look at a suggestion on the docs. 👍
