### ISSUE TITLE
daphne.server.current_reactor related issues

### ISSUE THREAD

**Issue by pppigg** [django/daphne#279]
I am now using the pyinstaller module for django project packaging.
There was a problem that caused websocket to become unusable：
`d:\envs\record\lib\site-packages\daphne\server.py:15: UserWarning: Something has already installed a non-asyncio Twisted reactor. Attempting to uninstall it; you can fix this warning by importing daphne.server early in your codebase or finding the package that imports Twisted and importing it later on.`
I look at these two problems[#793](https://github.com/django/channels/issues/793)[#195](https://github.com/django/daphne/issues/195),Then I tried putting channels at the top of INSTALL APPS.But it hasn't worked out...
I tried to print the value of current_reactor, it is <twisted.internet.selectreactor.SelectReactor object at 0x000001DC2B647710>.
Please give me a hand, thanks！

**Comment by carltongibson** [comment]
What's your main entry point? An `asgi.py`? At the top of that try `from daphne import server`. 

> you can fix this warning by importing daphne.server early in your codebase or finding the package that imports Twisted and importing it later on

Not really actionable beyond that.

**Comment by carltongibson** [comment]
(Are you importing twisted somewhere in your Django code, settings maybe?)

**Comment by pppigg** [comment]
@carltongibson Thank you for your answer.
I added the print information in daphne.server.
Indeed,I saw it before channels in the pyinstaller packaging.
Should I add `from daphne import server` now before it's first imported, Rather than after the packaging is complete

**Comment by SHxKM** [comment]
@pppigg - I’m facing the same issue, what ended up being the solution for you?

**Comment by pppigg** [comment]
@SHxKM It's unresolved. I've put it on hold.

**Comment by carltongibson** [comment]
Import daphne early in your entry point. That should resolve this.
