### ISSUE TITLE
daphne with django 3 

### ISSUE THREAD

**Issue by dimkoug** [django/daphne#292]
When i ran daphne with unix socket  and django version 3 i get this error  Django can only handle ASGI/HTTP connections, not websocket.

I try to run the django channels tutorial with  nginx gunicorn supervisor and daphne

**Comment by dimkoug** [comment]
ok i fixed it , i run the server via manage.py to ensure that works and then  fix the supervisor about daphne

**Comment by Sahil624** [comment]
Hi, I am facing this issue. It works fine on django built-in development server but it throws above error on daphne. I want to run my server on daphne instead of built-in dev server for production. 
Any help would be appreciated.

**Comment by dimkoug** [comment]
> Hi, I am facing this issue. It works fine on django built-in development server but it throws above error on daphne. I want to run my server on daphne instead of built-in dev server for production.
> Any help would be appreciated.

i will create a a basic project with celery and django channels

https://github.com/dimkoug/celeryproject

**Comment by louisliv** [comment]
I am also experiencing this error

Daphne is spitting out the same error:
Django can only handle ASGI/HTTP connections, not websocket.

**Comment by dwjorgeb** [comment]
> 
> 
> I am also experiencing this error
> 
> Daphne is spitting out the same error:
> Django can only handle ASGI/HTTP connections, not websocket.

@louisliv  getting the same issue. Did you manage to fix it?

**Comment by louisliv** [comment]
@dwjorgeb I did not. I can confirm it works using Django's runserver command instead of daphne, but I would prefer not to use Django's built in server for production.

**Comment by dwjorgeb** [comment]
@louisliv same, I can't use Django's built-in server for production. It's weird that I can't find any documentation, either on Channels or on Django about this apparent incompability

**Comment by Sahil624** [comment]
I managed to fix by using "get_default_application()" instead of "get_asgi_application()" in asgi.py . I don't have access to my system at this point to can't share exact code. Let me know if issue still persists.

**Comment by dwjorgeb** [comment]
@Sahil624 Where do you imported it? I don't have a `get_default_application`, only `get_asgi_application` and `get_wsgi_application`, neither of them work, as if I use wsgi one the server can't interact with it.

**Comment by Sahil624** [comment]
My `asgi.py` file looks like this.

``` python
"""
ASGI config for server project.
It exposes the ASGI callable as a module-level variable named ``application``.
For more information on this file, see
https://docs.djangoproject.com/en/3.0/howto/deployment/asgi/
"""

import os
import django

# from django.core.asgi import get_asgi_application
from channels.routing import get_default_application
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'server.settings')
django.setup()
# application = get_asgi_application()
application = get_default_application()
```

**Comment by louisliv** [comment]
@Sahil624 that worked for me.

**Comment by dwjorgeb** [comment]
@Sahil624 thanks, that actually worked for me. We can't use Django 3's ASGI file, we need to overwrite the ASGI file with the Channels' code (the one you put above, from here: https://channels.readthedocs.io/en/latest/deploying.html#run-protocol-servers )

thanks for pointing me in the right direction!

**Comment by carltongibson** [comment]
Django 3.0 does not support websockets. Continue to use Channels for this.

**Comment by Sahil624** [comment]
Glad it worked for all.

**Comment by KartheekL** [comment]
@Sahil624 can you help me with running a default method as soon as the server is run?

**Comment by debasisnath** [comment]
Sahil624  you save me. I am so thankful for what you did.
