### ISSUE TITLE
Custom TLS handshake with Daphne and Channels

### ISSUE THREAD

**Issue by MarcMueltin** [django/daphne#306]
Hi there, 

I am trying to figure out how I can use Channels (and Daphne) to write an authentication code that can handle three different security profiles for a WebSocket connection:
1. Unsecured Basic authentication headers (-> already works without problems)
2. TLS with Basic authentication headers (-> causes me headaches)
3. TLS with client-side certificate authentication (-> causes me headaches)

I have a feeling that I would be able to do what I want with the custom authentication described here: https://channels.readthedocs.io/en/latest/topics/authentication.html#custom-authentication

But I am still stuck. I want to define exactly
- which cipher suite the TLS server accepts
- which elliptic curve the TLS server uses for ECDHE (Elliptic Curve Diffie-Hellman Ephemeral)
- which ssl options to use (like "no compression")

I've set up the WebSocket CLIENT with an SSLContext (https://docs.python.org/3.8/library/ssl.html) like this:

```
ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
ssl_context.set_ciphers('ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384')
ssl_context.options |= ssl.OP_NO_COMPRESSION
ssl_context.set_ecdh_curve('prime256v1')
ssl_context.options |= ssl.OP_SINGLE_ECDH_USE
sl_context.load_cert_chain(get_file(path_to_certchain), get_file(path_to_privatekey))
ssl_context.verify_mode = ssl.CERT_REQUIRED
ssl_context.load_verify_locations(get_file(path_to_cabundle))

async with websockets.client.connect(
                uri=url,
                extra_headers=header,
                subprotocols=['some_subprotocol'],
                ssl=ssl_context) as websocket:
            global ws
            ws = websocket
            await asyncio.gather(on_open(websocket), on_message(websocket))
```

The same way I set the SSLContext for the client, I want to set it for the TLS server, which somehow will be provided by the combination of Channels and Daphne. 

So please, please tell me how I can achieve this. I've studied the Channels documentation for many hours but I can't seem to find a way to achieve what I want.

**Comment by carltongibson** [comment]
This isn't something I can advise you on I'm afraid. You'll need to look at Twisted's TLS docs[0] and then (probably) suggest a PR to Daphne. 

https://twistedmatrix.com/documents/current/core/howto/ssl.html

**Comment by MarcMueltin** [comment]
@carltongibson Thanks for the link.
Well, so far, for implementing the protocol I need to implement, I actually only need websockets, no http. What I was hoping for is something as simple as what the websockets library is providing in this example: https://websockets.readthedocs.io/en/stable/intro.html#secure-example

I guess I just need to quit thinking about Channels and Daphne, as it seems to be too much of an overkill and doesn't even provide me with the tools I need. 

Think the same?
