### ISSUE TITLE
Does daphne support multi-process?

### ISSUE THREAD

**Issue by Taikono-Himazin** [django/daphne#309]
The words may be strange because they use Google translation. sorry.

I'm asking a question because there are only a few articles about "daphne".
**Does daphne support multi-process?**
I originally thought to use uwsgi. However, due to complicated settings for websocekt using django channels, we will change uwsgi to daphne.
I want to do parallel processing to handle a lot of accesses. However, I could not find the option to make it multi-processed and multi-threaded like uwsgi.

Are there any options or equivalents for --processes or --threads in uwsgi?

**Comment by carltongibson** [comment]
See the Channels docs on Deployment https://channels.readthedocs.io/en/latest/deploying.html#deploying

You can run multiple processes, binding to either different ports or a shared file descriptor.
