### ISSUE TITLE
kubernetes command fix

### ISSUE THREAD

**Issue by grusirna** [django/daphne#312]
**kubernetes res**
      containers:
        - name: xxx
          image: xxx/xxx
          ports:
            - containerPort: 8000
          command:
            - daphne
            - -b 0.0.0.0
            - api:app

**error**
[api-774566f65b-mzz7s downloader] 2020-03-12 18:16:33,291 INFO     Configuring endpoint tcp:port=8000:**interface= 0.0.0.0**
[api-774566f65b-mzz7s downloader] 2020-03-12 18:16:33,292 CRITICAL Listen failure: Couldn't listen on  0.0.0.0:8000: [Errno -2] Name or service not known.

**look this**
interface= 0.0.0.0
This is strange.

**fix**
          command:
            - daphne
            - -b0.0.0.0
            - api:app

It wasn't a big deal, though it took hours. Hopefully it can help other users avoid this problem.

**Comment by adamchainz** [comment]
Thank you but closing since this seems quite specific to Kubernetes.
