### ISSUE TITLE
Add an option for auto-reloading.

### ISSUE THREAD

**Issue by c-bata** [django/daphne#313]
This is a feature request.

I want to add `--reload` option for auto-reloading. To detect the change of python files, the following implementation might be useful.
https://github.com/kobinpy/kwsgi/blob/master/kwsgi/reloader.py

Can I submit a pull request? If you don't have the motivation to add this feature, please feel free to close this issue.

**Comment by adamchainz** [comment]
Autoreloading is complex. I believe Channels' use of daphne reuses Django's built-in autoreloading machinery ([source](https://github.com/django/channels/blob/master/channels/management/commands/runserver.py)).

I'm not sure if it's in scope for Daphne to have such functionality too. You might be able to copy Channels' approach in a wrapper script using Django's autoloader or a similar library like pywatchman.

**Comment by c-bata** [comment]
Hi @adamchainz.
Thank you for your reply.

> I'm not sure if it's in scope for Daphne to have such functionality too. You might be able to copy Channels' approach in a wrapper script using Django's autoloader or a similar library like pywatchman.

Sounds reasonable. I close this.
