### ISSUE TITLE
--fd 0 , File descriptor Flag error while configuring Daphne for supervisor

### ISSUE THREAD

**Issue by yashrajvanshi** [django/daphne#321]
**settings at :/etc/supervisor/conf.d/odm.conf**

[program:odmasgi]

socket=tcp://localhost:8001

directory=/home/yashrajvanshi/ODM/ODM/offdutyservice/

**command=/home/yashrajvanshi/ODM/virtual/bin/daphne -u /run/daphne/daphne%(process_num)d.sock --fd 0 --access-log - --proxy-headers config.asgi:application**

numprocs=4

process_name=asgi%(process_num)d
autostart=true
autorestart=true

stdout_logfile=/home/yashrajvanshi/Desktop/odm-ws.log
redirect_stderr=true
~                                                                                                                                                                               
~

Running Above settings:
Throwing this error in odm-ws.log file
_Environ is...
config.settings.chat_settings
<channels.routing.ProtocolTypeRouter object at 0x7f44f55d8f98>
2020-06-01 13:58:44,130 INFO     Starting server at fd:fileno=0, unix:/tmp/daphne/daphne3.sock
2020-06-01 13:58:44,131 INFO     HTTP/2 support enabled
2020-06-01 13:58:44,131 INFO     Configuring endpoint fd:fileno=0
2020-06-01 13:58:44,139 CRITICAL Listen failure: [Errno 88] Socket operation on non-socket
2020-06-01 13:58:44,139 INFO     Configuring endpoint unix:/tmp/daphne/daphne3.sock_     

After removing --fd , Process runs smoothly.

**Comment by yashrajvanshi** [comment]
Issue Solved locally

**Comment by adamchainz** [comment]
Please post the solution for anyone else who comes across this
