### ISSUE TITLE
(Request) Add request method of GET to scope during websocket handshake in ws_protocol.py.

### ISSUE THREAD

**Issue by StefanCardnell** [django/daphne#330]
**My Setup**

Python 3.7 with following relevant packages:
```
daphne 2.5.0
channels-redis 3.0.1
channels 2.4.0
asgiref 3.2.10
```

**Issue / Feature request**

Inside `daphne.ws_protocol.WebSocketProtocol`, the scope supplied to the server application is not created with a `method` key of `GET` for the handshake of web socket protocols (starting line 72):

```py
self.application_deferred = defer.maybeDeferred(
                self.server.create_application,
                self,
                {
                    "type": "websocket",
                    "path": unquote(self.path.decode("ascii")),
                    "raw_path": self.path,
                    "headers": self.clean_headers,
                    "query_string": self._raw_query_string,  # Passed by HTTP protocol
                    "client": self.client_addr,
                    "server": self.server_addr,
                    "subprotocols": subprotocols,
                    # "method": "GET"  # <---- This is not supplied 
                },
            )
```

[As far as I can tell, websocket initial handshakes should be initially performed with a HTTP `GET` request](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers). This is certainly what I see from my browser console when initialising the websocket.

> Even though you're building a server, a client still has to start the WebSocket handshake process by contacting the server and requesting a WebSocket connection. So, you must know how to interpret the client's request. The client will send a pretty standard HTTP request with headers that looks like this (the HTTP version must be 1.1 or greater, **and the method must be GET**):

Can a `method` key with value `GET` therefore be placed in the scope context for websocket protocols?

**Use Case**

In middleware code, it is useful to create an `channels.http.AsgiRequest` object out of `self.scope` to easily access headers, cookies, query parameters, of the initial HTTP handshake ... instead of using `self.scope` directly. However `AsgiRequest(self.scope, io.BytesIO(b''))` fails in websocket context because of the missing `method` key from `self.scope` (which has ultimately been populated from `WebSocketProtocol`). 

**Workarounds**

Manually add `method` of `GET` to the scope before making the `AsgiRequest`.

**How you're running Channels** 

Daphne process behind Nginx

**Console logs and full tracebacks of any errors**

Error when trying to create `AsgiRequest(self.scope, io.BytesIO(b''))` in middleware for websocket protocols:

```
2020-09-08 15:31:25,967 [INF] runserver.log_action  WebSocket HANDSHAKING /socket/log-refresh/ [127.0.0.1:55354]
2020-09-08 15:31:26,582 [ERR] server.application_checker  Exception inside application: 'method'
Traceback (most recent call last):
  File "/var/www/webapps/migrater/backend/migrater/routing.py", line 142, in __call__
    return await inner(receive, send)
  File "/var/www/webapps/migrater/backend/migrater/routing.py", line 176, in __call__
    request = AsgiRequest(self.scope, io.BytesIO(b''))
  File "/home/vagrant/.local/share/virtualenvs/backend-W_smrMql/lib/python3.7/site-packages/channels/http.py", line 56, in __init__
    self.method = self.scope["method"].upper()
KeyError: 'method'
```

**Comment by adamchainz** [comment]
Adding "method" to the scope would be a change to the ASGI specification for websockets ([link](https://asgi.readthedocs.io/en/latest/specs/www.html#websocket-connection-scope), [repo](https://github.com/django/asgiref/)), rather than Daphne or Channels.

If the HTTP method is always predictable, I'm not sure it is really needed in the specification.

Perhaps channels' `AsgiRequest` class could provide support for Websockets scopes objects too, defaulting the method to GET. If that's all that's needed it is probably fairly okay to add, though I can't say I know too much about it. You'd really want to move this issue to Channels for that.

It would also be useful to know what other ASGI frameworks, such as Starlette, do here. Do they provide a request class that can read HTTP details from websockets scopes?

**Comment by carltongibson** [comment]
Closing per https://github.com/django/channels/pull/1497 Thanks.
