### ISSUE TITLE
Database connections persist forever when using CONN_MAX_AGE

### ISSUE THREAD

**Issue by whyscream** [django/daphne#332]
We're developing a django application with websockets. We use `daphne` to serve the whole application (no UWSGI component). Daphne is ran using `supervisor`, nginx proxies traffic to Daphne. OS is debian 9, python version is at 3.8.3

When we enable database connection caching in Django, open database connections to our PostgreSQL server are never ended. I would expect that a cache age of 10 seconds would result in less db connections some time after a peak volume of requests has been processed, and load has dropped. But the number of connections stays at the same high level. The only way to lower the number of open connections is by restarting daphne using supervisor.

Combined with https://github.com/django/daphne/issues/319, this results in a runaway number of database connections. On a platform where multiple websites handle peak volumes throughout the day, the number of database connections keeps growing until we reach the maximum the server will handle.

Sanitized output of `pip freeze`:
```
asgiref==3.2.10
channels==2.4.0
daphne==2.5.0
Django==2.2.16
psycopg2==2.8.6
sqlparse==0.3.1
```

**Comment by carltongibson** [comment]
Yep. OK. We need an alternate solution to the original threading issue there then.

**Comment by carltongibson** [comment]
This is the original issue https://github.com/django/channels/issues/1374
