### ISSUE TITLE
Why is daphne not logging using logging?

### ISSUE THREAD

**Issue by Taikono-Himazin** [django/daphne#333]
environment:
 django = 2.2.15
 daphne = 2.5.0

I built a logging system using python standard logging. It worked fine on runserver.
However, when started with the daphne command, it is no longer recorded in the access log file.
Upon closer examination, I found that only the access log of daphne uses AccessLogGenerator of access.py. I understand that it is for outputting in a form similar to NCSA format, but since this does not use the logging mechanism, even if "daphne" is specified in the logging handler, it will be ignored.
I know that you can write to a file with daphne's "--access-log" option, but that's not enough functionality. Also, only the access log has a different form from other log files.
Should AccessLogGenerator be an extension of logging, or at least an option to use logging?

If there is a way to incorporate such options and access logs into the logging mechanism, please let me know.

Thank you.

**Comment by carltongibson** [comment]
It probably could just use standard logging yes. (I'd say just an historical matter of fact that it is how it is…)

**Comment by Taikono-Himazin** [comment]
Yes. I want to apply it.

I want you to prepare such an option.
