### ISSUE TITLE
Deploy daphne on ubuntu

### ISSUE THREAD

**Issue by thanhtuyenpkk** [django/daphne#334]
Hi 
I create django project to write API.
I want deploy my project to EC2 ubuntu use daphne. But i don't know how.
Any one have document to deploy it, please sent for me!
Thanks you.

**Comment by adamchainz** [comment]
The django docs have a guide on deployment: https://docs.djangoproject.com/en/dev/howto/deployment/ . Underneath there is a short page on using daphne: https://docs.djangoproject.com/en/dev/howto/deployment/asgi/daphne/ 

Django's documentation can't go into the specifics of every operating system, version, etc. For more detail, search around for tutorials on the internet, e.g. Digital Ocean's ubuntu guides.
