### ISSUE TITLE
@app.on_event("startup/shutdown") ignored

### ISSUE THREAD

**Issue by paolo-prete** [django/daphne#349]
Hello. This is ignored at least on daphne 3.0.1. Tested with Ubuntu 18.04
----------------

from fastapi import FastAPI

app = FastAPI()

@app.on_event("startup")
async def startup_event():
  print("hello")

-------------------------------

**Comment by adamchainz** [comment]
Please provide a full replication project and the commands to run it.

**Comment by carltongibson** [comment]
But Daphne doesn't yet support lifespan events. 

There's an issue to add it in #264

**Comment by carltongibson** [comment]
Closing as a duplicate
