### ISSUE TITLE
Failed to update job template - Error: "Failed to update job template. PATCH returned status: 503"

### ISSUE THREAD

**Issue by Gopinath-G** [django/daphne#357]
#### Issue Type
- Bug Report

#### Component
- UI

#### Summary
Unable to update exiting template in UI, getting below error while I hit Save button

- Error: "Failed to update job template. PATCH returned status: 503"

#### Environment
- AWX Version : 15.0.1
- ansible : 2.9.14
- postgress: 10
-  Install method : Docker Compose
- Web browser: Google Chrome Version 88.0.4324.150

#### Steps to reproduce
Create a new job template and save
Edit the template to change any parameter and hit save 
This will report the given error

#### Expected Result
Template get updated with changes

#### Actual Result
![image](https://user-images.githubusercontent.com/65112067/107657049-c6c56f00-6caa-11eb-9212-09d8e188c5ea.png)

**Comment by Gopinath-G** [comment]
Apologize if this is wrong window intended to post in AWX community..

**Comment by carltongibson** [comment]
@Gopinath-G — Thanks for the follow-up. No problem. Good luck.
