### ISSUE TITLE
Make daphne startable from a python script

### ISSUE THREAD

**Issue by Nictec** [django/daphne#368]
Would it be easily possible to make it possible to import and start daphne from a python script? This would enable to deploy a django project stand alone without a application server that has to be installed besides the django-project.

**Comment by carltongibson** [comment]
Take a look at `daphne.cli` — it essentially just parses the CLI args and instantiates a `Server` instance with them. 

https://github.com/django/daphne/blob/e480917c1a68baf9beb5d8b61981750c4e49dcb0/daphne/cli.py#L262-L285

You could do similar. 

I'm going to close this. It's not really an issue, but interested to see what you come up with if you explore down this avenue.
