### ISSUE TITLE
NotImplementedError under windows 10

### ISSUE THREAD

**Issue by sirpatrick2** [django/daphne#370]
OS: Windows 10.0.19042 N/D build 19042
Python: 3.8.9
daphne==3.0.2
Django==3.2

Error:
Exception Type: NotImplementedError
python\python38\lib\asyncio\base_events.py, line 491, in _make_subprocess_transport

Code:
```
        proc = await asyncio.create_subprocess_exec(
            python_exe,
            bridge_script,
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
            )

```
I get the error running with daphne under windows. Under Linux everything goes OK, no errors.
Even under windows, launching with python manage.py runserver everything runs fine (no errors).

**Comment by synodriver** [comment]
This is because ```WindowsSelectorEventloop``` doesn't support this. ProactorEventloop do, but twisted doesn't support this eventloop, which daphne is built on.If you are using uvicorn, you can monkey patch it, however I just don't know if daphne can be monkey patched. ~~Maybe it's a mistake to run python on windows~~

**Comment by sirpatrick2** [comment]
I thought so. I use windows for just for develop/test and I wanted to keep the code as portable as possible between linux/windows. Maybe in the future there will be a common async process management, in the meantime I'll have to separate code for linux (using create_subprocess_exec) and windows (subprocess.Popen always flushing the stdin/stdout buffers from subprocess).
Thanks a lot for your explanation.
