### ISSUE TITLE
`Daphne` sets  `server='daphne'` header for `websocket` connections, but not for `http-requests`

### ISSUE THREAD

**Issue by baseplate-admin** [django/daphne#395]
# Hi there,

( Correct me if i am wrong here ) 
Daphne ( by default ) doesn't set a server header. 

By default these servers sets a header to identify backend technologies:
- [Uvicorn](github.com/encode/uvicorn) : uvicorn
- [Hypercorn](https://gitlab.com/pgjones/hypercorn) : hypercorn-{implementation}
- [Gunicorn](https://github.com/benoitc/gunicorn) : gunicorn/{version}

# Why should we do it ?
To allow technology detection by extensions like [Wappalyzer](https://github.com/AliasIO/wappalyzer/)

**Comment by adamchainz** [comment]
Ability to determine the underlying server is also a reason *not* to set a `Server` header, since it allows targeting servers when vulnerabilities become known.

**Comment by baseplate-admin** [comment]
Hi @adamchainz ,

Thanks for replying 😀

> The ability to determine the underlying server is also a reason not to set a ```Server`` header

While I agree with you on this but it doesn't contribute to a open web. Also most of the time Daphne is hidden behind a reverse proxy ( for which setting server header wont do much unless its a transparent proxy ). Its only for websites that are served with Daphne.

>  since it allows targeting servers when vulnerabilities become known

I totally agree with this. So we can add an option ( or use a django middleware to modify the headers )  to disable header for mission critical servers.

eg:
```python
if SERVER_HEADER_HIDDEN:
       headers.pop('Server')
```

> At least we should not report the version of Daphne.

Agreed. None of the above mentioned server shows version. ( Except Gunicorn )

**Comment by baseplate-admin** [comment]
Also it should be noted that Daphne already shows server header. Check [here](https://github.com/django/daphne/blob/6a5093982ca1eaffbc41f0114ac5bea7cb3902be/daphne/server.py#L59) [here](https://github.com/django/daphne/blob/6a5093982ca1eaffbc41f0114ac5bea7cb3902be/daphne/server.py#L84) and its getting invoked for **Websocket** requests [only](https://github.com/django/daphne/blob/6a5093982ca1eaffbc41f0114ac5bea7cb3902be/daphne/server.py#L95).

As expected it works for websocket connections : 
![Daphne](https://user-images.githubusercontent.com/61817579/147556001-85aa2123-2061-4db6-8734-293f31eb727e.PNG)

But it doesn't work for Http request : 
![e](https://user-images.githubusercontent.com/61817579/147556032-a7d309c1-9461-4072-a9d4-2904af5d1c7f.PNG)

**Comment by adamchainz** [comment]
Okay, if we're already doing it I don't see a reason not to add it to HTTP responses.

Could you look into a PR?

**Comment by baseplate-admin** [comment]
Sure. Let me take a look. 🥳

**Comment by baseplate-admin** [comment]
Hi i took a look and it seems that this function is useless.
```python
if self.server.server_name and self.server.server_name.lower() != "daphne":
        self.setHeader(b"server", self.server.server_name.encode("utf-8"))
```
I replaced it and it works perfectly.
