### ISSUE TITLE
pre-commit failing

### ISSUE THREAD

**Issue by adamchainz** [django/daphne#397]
It looks like the pre-commit GitHub action is failing to install setuptools properly: https://github.com/django/daphne/actions/workflows/pre-commit.yml

The action is deprecated: https://github.com/pre-commit/action

I suggest we switch to using https://pre-commit.ci

**Comment by adamchainz** [comment]
Turns out I have permission to do this - but I don't want to just commit (heh) to it, especially since the issue I opened on Django ( https://github.com/django/django/pull/15178 ) hasn't seen any response.

Any thoughts @carltongibson ?

**Comment by carltongibson** [comment]
> Any thoughts @carltongibson ?

😝 

Little bit sceptical about the value-add for django/django **but** if you want to give it a run here, that's fine I guess. It maybe a raging success and convert the sceptics. 

Thanks @adamchainz

**Comment by carltongibson** [comment]
Hey @adamchainz -- shall we give this a go here, and on Channels and channels_redis? Gives us a fair taste, independently of django/django
