### ISSUE TITLE
Daphne logger(s) not set up to handle error output

### ISSUE THREAD

**Issue by ssteinerx** [django/daphne#43]
I have a Twisted Looping call that pumps out the current time (from a Django app).

If I set that Looping call so it's sending out a bad key (before it's ever called), then load the page that causes that Looping call to start, the first time it tries to send, I get this:

```
[2016/09/11 16:21:27] WebSocket CONNECT /liveblog/ssteinerx-live-blog/stream/ [127.0.0.1:50558]
('Trying to create channel for:', u'ssteinerx-live-blog')
[2016/09/11 16:21:27] WebSocket CONNECT /update_time/stream/ [127.0.0.1:50560]
('Adding update_time group...', <channels.channel.Channel object at 0x000000010a7ca330>)
{'time': '2016-09-11 16:21:27.696304'}
LoopingCall started...
No handlers could be found for logger "daphne.server"
{'time': '2016-09-11 16:21:28.697522'}
```

This is 100% repeatable. Yay. If the logger is set up and ready to roll on the next bad call, I don't know, but the "No handlers..." message does not repeat.

There is no handler for the logger's `error()` call.

So, this:

```
Python 2.7.10 (0e2d9a73f5a1818d0245d75daccdbe21b2d5c3ef, Sep 07 2016, 19:23:10)
[PyPy 5.4.1 with GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>> import logging
>>>> l = logging.getLogger(__name__)
>>>> l.debug("Debugooy")
>>>> l.info("Infoooy")
>>>> l.warn("Warnooy")
>>>> l.error("Ahfooey")
No handlers could be found for logger "__main__"
```

The reason the message about the handler is coming out at all [logging doc on this](https://docs.python.org/2/howto/logging.html#what-happens-if-no-configuration-is-provided)

The error() handler needs to be configured with destination for the logger.error in server.py (and probably elsewhere as well). Not sure how you want it handled, but it has to be explicitly handled. The error message only appears once, but I'm pretty sure the rest of those logger.error() calls are just falling on the floor, so they need to be hooked up to something. Who knew?

**Comment by ssteinerx** [comment]
@andrewgodwin  If you tell me how you want to handle this, I'll take care of it wherever the change is necessary.

**Comment by andrewgodwin** [comment]
The logging is already configured to output to the console, either in daphne.cli (https://github.com/django/daphne/blob/2176b209f71b4bb996dcbcba2048aeeadbd4168d/daphne/cli.py#L114) or in runserver (https://github.com/django/channels/blob/master/channels/management/commands/runserver.py#L30), so it's not the problem you described, I don't think.

**Comment by ssteinerx** [comment]
This is not happening when I `setup.py develop` both channels and daphne so it's probably, as you said, fixed though it was happening when I had installed with pip.  I'm going to close this and will test again with the next PyPI releases.
