### ISSUE TITLE
can't access via LAN

### ISSUE THREAD

**Issue by gyorokpeter** [django/daphne#431]
Originally I was running daphne with just "daphne ...:application". It listens on port 8000 and is reachable from "localhost" or "127.0.0.1" but not when I use my computer's IP address. It is also unreachable from other devices on the network.
On the other hand, I can start another app and have it listen on port 8000, and that will succeed (it doesn't fail with "address already in use") and the resulting process is reachable from the network. Therefore it seems it's daphne's config that is not correct. I tried playing around with the -b option but it doesn't seem to take effect, even in TCPView it is shown as listening on 0.0.0.0:8000 for any value of -b.

**Comment by carltongibson** [comment]
This looks like something particular to your setup... 🤔

I'm able to bind to `0.0.0.0:8000` and access over the local network no problem. 

Short of something more concrete I don't think I can help. Sorry.
