### ISSUE TITLE
Does daphne have a file for initialization？

### ISSUE THREAD

**Issue by Alien-2022** [django/daphne#469]
Does daphne have a file for initialization, so I don't have to type a lot of code on the command line every time I start the server

**Comment by carltongibson** [comment]
No, it doesn't (yet). Normally you'd write a wrapper script for too many CLI options. 

I'm not anti this as an idea if someone wants to add it, but pending a PR, I'm not going to consider it an open issue. 
I'll close on that basis. Happy to reopen if that PR appears.
