### ISSUE TITLE
Requests with Transfer-Encoding: chunked have no content

### ISSUE THREAD

**Issue by tfeldmann** [django/daphne#476]
I guess I'm a bit confused by now.
According to the ASGI spec the server should handle (dechunk?) incoming requests.

So I've written a small django app with this view:

```python
import logging

from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt


@csrf_exempt
def index(request):
    print("META", request.META)
    print("GET", request.GET)
    print("POST", request.POST)
    print("FILES", request.FILES)
    if request.method == "POST":
        logging.info(request.__dict__)
        return HttpResponse("END_OK\n")
    else:
        return HttpResponse("ok")
```

Starting daphne with `daphne myapp.asgi:application -p 8080` and execute a curl request with 

```sh
curl \
    -H "User-Agent: MyAgent ()" \
    -H "Transfer-Encoding: chunked" \
    -F  "file=@/Users/tf/Pictures/gravatar.jpeg" \
    http://localhost:8080/sync
```

Results in:

```
META {'REQUEST_METHOD': 'POST', 'QUERY_STRING': '', 'SCRIPT_NAME': '', 'PATH_INFO': '/sync/', 'wsgi.multithread': True, 'wsgi.multiprocess': True, 'REMOTE_ADDR': '127.0.0.1', 'REMOTE_HOST': '127.0.0.1', 'REMOTE_PORT': 65074, 'SERVER_NAME': '127.0.0.1', 'SERVER_PORT': '8080', 'HTTP_HOST': 'localhost:8080', 'HTTP_ACCEPT': '*/*', 'HTTP_USER_AGENT': 'MyAgent ()', 'HTTP_TRANSFER_ENCODING': 'chunked', 'CONTENT_TYPE': 'multipart/form-data; boundary=------------------------410f03697d6bfef5'}
GET <QueryDict: {}>
POST <QueryDict: {}>
FILES <MultiValueDict: {}>
```

Doing the same in waitress (which dechunks the request) results in:

```
META {'REMOTE_ADDR': '127.0.0.1', 'REMOTE_HOST': '127.0.0.1', 'REMOTE_PORT': '65077', 'REQUEST_METHOD': 'POST', 'SERVER_PORT': '8080', 'SERVER_NAME': 'waitress.invalid', 'SERVER_SOFTWARE': 'waitress', 'SERVER_PROTOCOL': 'HTTP/1.1', 'SCRIPT_NAME': '', 'PATH_INFO': '/sync/', 'REQUEST_URI': '/sync/', 'QUERY_STRING': '', 'wsgi.url_scheme': 'http', 'wsgi.version': (1, 0), 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>, 'wsgi.multithread': True, 'wsgi.multiprocess': False, 'wsgi.run_once': False, 'wsgi.input': <_io.BufferedRandom name=9>, 'wsgi.file_wrapper': <class 'waitress.buffers.ReadOnlyFileBasedBuffer'>, 'wsgi.input_terminated': True, 'HTTP_HOST': 'localhost:8080', 'HTTP_ACCEPT': '*/*', 'HTTP_USER_AGENT': 'MyAgent ()', 'CONTENT_TYPE': 'multipart/form-data; boundary=------------------------428cf6133f9ea7bf', 'CONTENT_LENGTH': '573892', 'waitress.client_disconnected': <bound method HTTPChannel.check_client_disconnected of <waitress.channel.HTTPChannel connected 127.0.0.1:65077 at 0x10448e7d0>>}
GET <QueryDict: {}>
POST <QueryDict: {}>
FILES <MultiValueDict: {'file': [<InMemoryUploadedFile: gravatar.jpeg (image/jpeg)>]}>
```

What am I doing wrong here?

**Comment by carltongibson** [comment]
Can you check that the `request.body` is actually set correctly (prior to file parsing)?

**Comment by carltongibson** [comment]
OK, so there's some weirdness as to why it's not getting out of Django's `HttpRequest._load_post_and_files()` then (I think)

**Comment by tfeldmann** [comment]
Yes, probably. I tried it with something more managable:

```
body b'--------------------------2c8edae761a97569\r\nContent-Disposition: form-data; name="file"; filename="Hello.txt"\r\nContent-Type: text/plain\r\n\r\nHello World!\n\r\n--------------------------2c8edae761a97569--\r\n'
META {'REQUEST_METHOD': 'POST', 'QUERY_STRING': '', 'SCRIPT_NAME': '', 'PATH_INFO': '/sync/', 'wsgi.multithread': True, 'wsgi.multiprocess': True, 'REMOTE_ADDR': '127.0.0.1', 'REMOTE_HOST': '127.0.0.1', 'REMOTE_PORT': 49220, 'SERVER_NAME': '127.0.0.1', 'SERVER_PORT': '8080', 'HTTP_HOST': 'localhost:8080', 'HTTP_ACCEPT': '*/*', 'HTTP_USER_AGENT': 'SmartLink ()', 'HTTP_TRANSFER_ENCODING': 'chunked', 'CONTENT_TYPE': 'multipart/form-data; boundary=------------------------2c8edae761a97569'}
GET <QueryDict: {}>
POST <QueryDict: {}>
FILES <MultiValueDict: {}>
```

**Comment by tfeldmann** [comment]
I cannot say what exactly is going on. The above code is enough to reproduce the issue, but I'm happy with providing a full project for this if needed?

**Comment by tfeldmann** [comment]
In the spec it says (https://asgi.readthedocs.io/en/latest/specs/www.html#http-connection-scope):
> Servers are responsible for handling inbound and outbound chunked transfer encodings. A request with a chunked encoded body should be automatically de-chunked by the server and presented to the application as plain body bytes; a response that is given to the server with no Content-Length may be chunked as the server sees fit.

I don't know how hypercorn / uvicorn handle this.

**Comment by carltongibson** [comment]
Yes... 🤔 The interesting one was that the body makes it (as far as we're aware). 

(I need time to sit down with the debugger to be able to say more, but that's the question I'm asking first.)

**Comment by agronick** [comment]
I think this is a Django bug and I opened a ticket [here](https://code.djangoproject.com/ticket/35289?replyto=3#comment). Transfer-encoding chunked should not have a content length per the HTTP spec but Django only uses the content-length for determining if uploaded files should be processed. There is a conditional in Django that gives up on uploaded files if the content-length is 0. You can make a middleware to spoof the content length to 1 if the `transfer-encoding` is `Chunked` e.g.:
```py
        if request.headers["Transfer-Encoding"] == "chunked" and "CONTENT_LENGTH" not in request.META:
            request.META["CONTENT_LENGTH"] = "1"
```

 and everything works correctly. You'll also want to set your `FILE_UPLOAD_HANDLERS` to just `"django.core.files.uploadhandler.TemporaryFileUploadHandler"` because the `MemoryFileUploadHandler` is just looking at the content-length.

**Comment by nessita** [comment]
Thank you @agronick for posting here, I was in the middle of my investigation to triage your Django ticket. I also found the (I think) related issue #371.

**Comment by zoobab** [comment]
@agronick do you have a patch example that works for you? Is there a patch to django code yet?

**Comment by matthew-pest** [comment]
Was using ky to post json to django from a nextjs 15.3 app. Ran into this Transfer-Encoding "chunked" + Content-Length 0 issue as well. Seems its a WSGI limitation but simply running an ASGI server did not automatically resolve the issue.

Solved with middleware. Using Django 5.2.1 and Uvicorn 0.34.2 (A bit of research and lot of feeding this thread into cursor - https://code.djangoproject.com/ticket/35289)

@sync_and_async_middleware
def chunked_content_length_middleware(get_response):
    def needs_content_length(request):
        # Only patch if Transfer-Encoding is chunked and CONTENT_LENGTH is missing or empty
        return (
            request.headers.get("Transfer-Encoding", "").lower() == "chunked"
            and not request.META.get("CONTENT_LENGTH")
        )

    async def async_middleware(request):
        if needs_content_length(request):
            request.META["CONTENT_LENGTH"] = "1"
        return await get_response(request)

    def sync_middleware(request):
        if needs_content_length(request):
            request.META["CONTENT_LENGTH"] = "1"
        return get_response(request)

    # Django will pick the right one
    return async_middleware if hasattr(get_response, "__call__") and hasattr(get_response, "__await__") else sync_middleware


This was then set as the first entry in my settings.py middleware list

MIDDLEWARE = [
    "bloxoffice.middleware.chunked_content_length_middleware",
    ...
]

Hope this can help someone else!
