### ISSUE TITLE
Daphne not working when run as Systemd service in RHEL

### ISSUE THREAD

**Issue by schizo99** [django/daphne#49]
Hi,

I'm having issues running daphne as a unit in systemd.
It works great when executed interactively. 
If anyone has input this would be highly appreciated.

```
[Unit]
Description=Daphne Web Server
After=network.target

[Service]
Type=simple
User=daphne
Group=daphne
WorkingDirectory=/project
ExecStart=/project/bin/daphne -b 0.0.0.0 -p 8080 --root-path=/project asgi:channel_layer
Restart=always

[Install]
WantedBy=multi-user.target

```
When started, it starts fine, via systemd all I get is a 404.

**Comment by andrewgodwin** [comment]
Do you get an 404 from Daphne, from Django, or from another webserver in between? It's likely your setup rather than systemd in particular.

**Comment by schizo99** [comment]
Sorry, the 404 is delivered from Django.

After tinkering a little bit I realized the only thing differing between the way I started interactively and systemd was the --root-path. After removing it is now working.
