### ISSUE TITLE
python manage.py runserver not working

### ISSUE THREAD

**Issue by IMOWWW** [django/daphne#508]
I have everything set up correctly, but the project does not run as async

System check identified no issues (0 silenced).
April 10, 2024 - 18:56:40
Django version 4.2.8, using settings 'ChatProject.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

**Comment by IMOWWW** [comment]
I solved this problem by changing the version from daphne==4.1.1 to daphne==4.0.0

**Comment by carltongibson** [comment]
OK, this works for me with 4.1.0, but not 4.1.1. 

Let's reopen: it's not fixed by you reverting to an earlier version.

**Comment by 1One0** [comment]
I met the same problem when i update daphne version, 4.1.1 package missing `management/commands/runserver.py` so `runserver` wont work with daphne.

**Comment by carltongibson** [comment]
@1One0 Thanks for confirming. 

4.1.1 fixed one packaging issue in 4.1.0, only to introduce another. (Never change the packaging 🤦) 

Fix coming later today.

**Comment by joseseb91** [comment]
would be helpful if it was mentioned in changelog of 4.1.2 that runserver doesnt work with daphne 4.1.1, spent two days rewriting django channels setup to figure out why websockets were not working, 

was working with docker base images and my dev server build from last week was using 4.1.1 :cry:
our staging server base img had 4.1.0
