### ISSUE TITLE
Daphne - Twisted custom cipher list using set_cipher method

### ISSUE THREAD

**Issue by KaviHarjani** [django/daphne#511]
I have got a web app in production and it uses Daphne to run it 

I want to limit ciphers it accepts, I can do so directly in twisted but cannot do that in Daphne

Would migrating to twisted if only using http http2 and not web sockets, have any effect on the app?

Is there a way to set custom ciphers list on Daphne?

**Comment by carltongibson** [comment]
This looks like it would need you https://github.com/twisted/twisted/pull/12137 to be merged no?

**Comment by KaviHarjani** [comment]
Ah yes, actually raised this issue before raising the PR there haha

**Comment by carltongibson** [comment]
Ok, let's close in favour of the upstream issue. Thanks.
