### ISSUE TITLE
Why Daphne creates an app for every WebScoket connection

### ISSUE THREAD

**Issue by Fly-Playgroud** [django/daphne#516]
https://github.com/django/daphne/blob/4a55faca45db2e2a4c275ee02c44893e6af0b5c7/daphne/ws_protocol.py#L74
Why is it designed like this?This would mean there are many APP instances！！！

**Comment by carltongibson** [comment]
That's [how ASGI works](https://asgi.readthedocs.io/en/latest/introduction.html#how-does-asgi-work) — that's the spec for the protocol.
