### ISSUE TITLE
Daphne: Cannot acquire lock

### ISSUE THREAD

**Issue by socketopp** [django/daphne#519]
Currently get the following issue:

> 2024-07-29 15:35:41 2024-07-29 13:35:41,580 INFO     Starting server at tcp:port=8000:interface=0.0.0.0, unix:/tmp/daphne.sock
> 2024-07-29 15:35:41 2024-07-29 13:35:41,581 INFO     HTTP/2 support enabled
> 2024-07-29 15:35:41 2024-07-29 13:35:41,581 INFO     Configuring endpoint tcp:port=8000:interface=0.0.0.0
> 2024-07-29 15:35:41 2024-07-29 13:35:41,593 INFO     Listening on TCP address 0.0.0.0:8000
> 2024-07-29 15:35:41 2024-07-29 13:35:41,593 INFO     Configuring endpoint unix:/tmp/daphne.sock
> 2024-07-29 15:35:41 2024-07-29 13:35:41,594 CRITICAL Listen failure: Couldn't listen on any:b'/tmp/daphne.sock': Cannot acquire lock.

See issue on [Django channels](https://github.com/django/channels/issues/642)

Daphne doesn't delete daphne.sock.lock after emergence shutdown.

I run daphne like this:
```
command: >
  sh -c "rm -f /tmp/daphne.sock && python manage.py makemigrations && python manage.py migrate &&
        daphne -b 0.0.0.0 -p 8000 django_server.asgi:application"
 ```
 
 Any ideas on how to resolve this?

**Comment by carltongibson** [comment]
> `rm -f /tmp/daphne.sock` 

That should work to get you up and running, yes. 

> Any ideas on how to resolve this?

Depends what you mean by `emergence shutdown` — If you don't let Daphne exit cleanly it can't clear up after itself. Open to ideas. 💡

**Comment by socketopp** [comment]
> > `rm -f /tmp/daphne.sock`
> 
> That should work to get you up and running, yes.
> 
> > Any ideas on how to resolve this?
> 
> Depends what you mean by `emergence shutdown` — If you don't let Daphne exit cleanly it can't clear up after itself. Open to ideas. 💡

> 
>     rm -f /tmp/daphne.sock
> 
> That should work to get you up and running, yes.

I've tried that but it didn't help. Only thing that worked was to delete my container and rebuild from scratch with

`docker-compose down --volumes --remove-orphans`

**Comment by carltongibson** [comment]
@socketopp OK, I can't really help. This seems like a docker issue... — I'd advise working out what to do locally, and then translating that to your container's filesystem. 

Closing as not an issue with Daphne per se.
