### ISSUE TITLE
Running multiple instances of Daphne behind a load balancer (Nginx).

### ISSUE THREAD

**Issue by furious-luke** [django/daphne#52]
Hi there,

Just wondering whether Daphne correctly handles routing of responses in an environment where multiple instances of Daphne may be servicing requests/responses simultaneously against a single channel layer? I was hoping to be able to have multiple Daphne instances running behind Nginx in order to have fail-overs and load balancing in situations where a lot of data is being returned. Each of the Daphne instances would be connected to the same pool of workers behind a Redis server.

Thanks!
Luke

**Comment by JohnDoee** [comment]
It's designed to handle that exact situation. The messages are sent from Django to Daphne through a channel only the correct Daphne listens to.

**Comment by furious-luke** [comment]
@JohnDoee Thanks for the quick response! Just wondering whether you might be able to direct me to how Daphne does this? I've been looking through the code and haven't been able to identify the mechanism. Cheers!

**Comment by JohnDoee** [comment]
The ASGI specs is the best place for this.

A bit about messages: https://channels.readthedocs.io/en/stable/asgi.html#message-formats

The quote answering your question:
> In order to aid with scaling and network architecture, a distinction is made between channels that have multiple readers (such as the http.request channel that web applications would listen on from every application worker process), single-reader channels that are read from a single unknown location (such as http.request.body?ABCDEF), and process-specific channels (such as a http.response!ABCDEF channel tied to a client socket).

It might be helpful to monitor redis (login with redis-cli and type monitor) to see what's really going on.

**Comment by furious-luke** [comment]
Hmm, it's still not clear to me from that excerpt (and the ASGI specs). It seems to suggest the multiple readers are the "application worker processes", which in my mind are the workers, not Daphne. Perhaps the part about being "tied to a client socket" is the mechanism?

I'll take a look at the Redis messages directly and see if it makes it any clearer.

**Comment by furious-luke** [comment]
Waaaait, I get it, all good! The channels read by Daphne are limited by the locally known set of reply channels:

```
channels = self.factory.reply_channels()
...
channel, message = self.channel_layer.receive_many(channels, block=False)
```

And this is unique amongst Daphne clients due to the exclamation point used here,

```
self.reply_channel = self.factory.channel_layer.new_channel("http.response!")
```

which causes the `asgi_redis` layer to add random characters to the channel name.

Thanks for your help!
