### ISSUE TITLE
missing file for tests in pypi distfile

### ISSUE THREAD

**Issue by 0-wiz-0** [django/daphne#522]
When running the self tests from the pypi distfile, I see:
```
ImportError while importing test module '/scratch/www/py-daphne/work/daphne-4.1.2/tests/test_websocket.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/pkg/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_websocket.py:5: in <module>
    import http_strategies
E   ModuleNotFoundError: No module named 'http_strategies'
```
The file http_strategies.py is missing from the pypi (4.1.2) distfile. Please add it.

**Comment by bigfootjon** [comment]
@carltongibson how do you feel about including the tests in the pypi package?

**Comment by carltongibson** [comment]
@bigfootjon No problem: they're useful for OS package maintainers, who like to run the tests (rightly) 

I looked at this briefly: the tests are there, but we're missing the `http_base.py` and `http_strategies.py` files from the test folder. (Likely the discovery rule says, begins with `test_`...)

**Comment by bigfootjon** [comment]
see: https://github.com/django/daphne/pull/530

**Comment by 0-wiz-0** [comment]
Thank you, @bigfootjon !
