### ISSUE TITLE
access log is not line buffered

### ISSUE THREAD

**Issue by stratoukos** [django/daphne#53]
Daphne has an option to log requests to a file. That file is opened using the default system buffering and is never flushed to disk, so log entries are appended to the log file only when that buffer fills up, or when Daphne restarts.

The file should probably be line buffered since log entries should appear as soon as they happen.

**Comment by carltongibson** [comment]
Hmmm. I'm still seeing this issue with daphne==0.15.0 — Ah. That's because I see #54 was subsequent to that. Fine.
