### ISSUE TITLE
Ensure single on websocket connections

### ISSUE THREAD

**Issue by johanneswilm** [django/daphne#531]
Hey,
I am working on [Fidus Writer,](https://github.com/fiduswriter/fiduswriter) a realtime document editor. After looking through the entire documentation and spending a lot of time switching from tornado/django to django channels, [I ended up deciding that channel layers doesn't make sense for our usecase](https://github.com/fiduswriter/fiduswriter/pull/1294). The redis server and communication back and forth, etc. are just too much of an overhead when it comes to realtime document collaboration where the number of simultaneous editors of a document will be limited. 

However, I would still like to sue Django Channels. So what I want to make sure is that **every connection made to the same port with a  Daphne instance will connect with the same thread**. I couldn't find anything in the documentation saying this is the case or isn't the case.

I am imagining setting up an NGINX configuration looking something like this:

```
upstream channels-backend {
    server localhost:8000;
    server localhost:8001;
    server localhost:8002;
    server localhost:8003;
}
...
server {
    ...
    location / {
        proxy_pass http://channels-backend;

        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $server_name;
    }
    ...
    location /ws0/ {
        proxy_pass http://localhost:8000/ws/;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
    ...
    location /ws1/ {
        proxy_pass http://localhost:8001/ws/;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
    ...
    location /ws2/ {
        proxy_pass http://localhost:8002/ws/;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
    ...
    location /ws3/ {
        proxy_pass http://localhost:8003/ws/;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
 
}
```

The above configuration may still need some adjustments, but hopefully you get what I mean. I need to make sure that all the connecting to the daphne available through `/ws3/` can talk to oneanother without having to go through Redis or similar. So it's important for me that daphne doesn't just start creating new processes/threads by itself somehow. Is that either the case by default or can daphne be made to behave in this way?

**Comment by carltongibson** [comment]
If you can send all requests to the same Daphne process then the in-memory channel layer might just do you. 🤔

**Comment by johanneswilm** [comment]
@carltongibson Right, but so the question is then - can I be sure that one daphne process on one port will really only be one workedr/process/thread? 

And once I have that, I don't really have any advantage of using the layers mechanism at all, do I?

Right now I do

```py

class MyConsumer(WebsocketConsumer):
    clients = []
    documents = {}
    
    def connect(self):
        MyConsumer.clients.append(self)
        self.document_id = int(
            self.scope["url_route"]["kwargs"]["document_id"]
        )
        if self.document_id not in MyConsumer.documents:
            MyConsumer.documents[self.document_id] = {"type": "doc", "content": [...]}
        self.document = MyConsumer.documents[self.document_id]
     
    def disconnect(self, close_code):
        MyConsumer.clients.remove(self)
        self.close()
   
    ...
    
    def some_function(self):
        for client in MyConsumer.clients:
            client.another_function(...)
```

The above is a bit simplified, but it should show that that way I can share the document objects between all clients that connect to the same process so that all I need to make sure is that all users who want to edit for example document 8 connect to `/ws3/` to do so.

I did not find a way to share objects between users using the channel layer system, at least not in version 4. It all seemed to be about sharing messages, not about sharing objects.

**Comment by carltongibson** [comment]
@johanneswilm Yeah, it's not really designed that way. 

But — kind of the whole point of ASGI — a Daphne instance runs a single worker thread, running an event loop, and so I can't really see why what you've described wouldn't work. 

Of course, if you don't like the channel layer abstraction, you could write to/read from some shared storage yourself. The selling point of cooperative multitasking like this is that you know nobody else is touching that memory until you return control back to the event loop with an `await`.

**Comment by johanneswilm** [comment]
@carltongibson Ok, thanks! That's very helpful information.

What I didn't like about running Tornado in combination with Django (for close to ten years) was that it was a very unique setup that was never guaranteed to work with new Django or Tornado releases and very difficult to read for others. It sounds like this new solution - using Django Channels but without layers and instead our own storage and request routing system - is the best combination currently possible that combines following the Django way of doing things as much as possible while not having to overly complicate the setup and eat memory and processing power by having every client keeping separate copies of everything in memory.

**Comment by carltongibson** [comment]
@johanneswilm Let us know what you come up with!
