### ISSUE TITLE
Use X-Forwarded-For headers to populate client addr

### ISSUE THREAD

**Issue by stratoukos** [django/daphne#55]
Daphne uses the incoming connection's address and port to determine the `client_addr`, which obviously don't exist when listening to a unix socket. When listening to a unix socket we can assume that there's a reverse proxy in front of Daphne so we can check for "X-Forwarded-For" and "X-Forwarded-Port" headers and log those, if they exist.

Also, I'm not sure it's useful to log client ports. It's almost certainly going to be a high random port in both cases. Looking at other servers for reference, neither apache nor nginx seem to log the client port by deafult.

**Comment by andrewgodwin** [comment]
The default configuration shouldn't be interpreting forwarded headers for the log - that would be the job of custom log formatting IMO. I'm not sure what the bug is here - the client address is logged as None on a socket as there is no source address; should it be logged as the socket path instead maybe?

**Comment by stratoukos** [comment]
To be honest, I expected Daphne to log the original connection's IP address in the first place.

Assuming that Daphne is supposed to sit behind a reverse proxy, I don't thing it's unreasonable to interpret forwarded headers in the default configuration, even when Daphne is listening to a TCP socket. Otherwise the address in the log file is not very useful since it's always going to be the IP of the reverse proxy/load balancer (or None when listening to a unix socket). This is what uWSGI does by default, for example, which seems to occupy a similar spot (in a wsgi stack) with Daphne (in an asgi one).

**Comment by andrewgodwin** [comment]
Fair enough - if uwsgi does it it's not unreasonable (I was thinking of e.g. nginx where you have to explicitly specify it). I won't have time to work on this myself in the near future but any contributions are welcome.

**Comment by raphaelm** [comment]
I'd be interested in working on this :)

**Comment by andrewgodwin** [comment]
Note: We've decided at the DUTH sprints we'll include `X-Forwarded-Port` along with `For`, and have it off by default but switch on with a single CLI flag.

**Comment by pztrick** [comment]
Just a `+1` to making the default to use the `X-Forwarded` headers. 😄 

Logging `127.0.0.1:xxxxx` isn't very useful and Daphne could at least introspect if it's a local host and check for `X-Forwarded` headers to use. That said, just enabled the CLI flag here. :)
