### ISSUE TITLE
-e unrecognized arguments

### ISSUE THREAD

**Issue by remusmp** [django/daphne#64]
Hello,

I tried to run `daphne` using the following command:

> daphne -e ssl:443:privateKey=my.key:certKey=my.crt app.asgi:channel_layer

I'm getting the following error:

> usage: daphne [-h] [-p PORT] [-b HOST] [-u UNIX_SOCKET] [--fd FILE_DESCRIPTOR]
>               [-v VERBOSITY] [-t HTTP_TIMEOUT] [--access-log ACCESS_LOG]
>               [--ping-interval PING_INTERVAL] [--ping-timeout PING_TIMEOUT]
>               [--ws-protocol [WS_PROTOCOLS [WS_PROTOCOLS ...]]]
>               [--root-path ROOT_PATH]
>               channel_layer
> daphne: error: unrecognized arguments: -e webapp.asgi:channel_layer

`pip list` shows the following installed packages:

> asgi-redis (1.0.0)
> asgiref (1.0.0)
> autobahn (0.17.1)
> channels (0.17.3)
> constantly (15.1.0)
> daphne (0.15.0)
> Django (1.10.4)
> django-sslserver (0.19)
> djangorestframework (3.5.3)
> incremental (16.10.1)
> msgpack-python (0.4.8)
> Pillow (3.4.2)
> pip (9.0.1)
> redis (2.10.5)
> reportlab (3.3.0)
> setuptools (31.0.0)
> six (1.10.0)
> Twisted (16.6.0)
> txaio (2.6.0)
> wheel (0.30.0a0)
> zope.interface (4.3.3)

Everything works fine without ssl.

**Comment by andrewgodwin** [comment]
The `-e` flag is not yet in a released version, so it's not going to work yet unless you run from master. I'm hoping to release a new version soon, I just need to coordinate it properly with a channels release.
