### ISSUE TITLE
Are workers multithreaded?

### ISSUE THREAD

**Issue by saurabhkumargangwar** [django/daphne#69]
We have 7 workers running on production. We see linear time increase as the number of request per second increases. 
If suppose there are X workers, does that mean only X number of request can be handled at a time and all other requests will be queued which in turn will increase the response time ?

**Comment by andrewgodwin** [comment]
Django workers (those run with `manage.py runworker`) are single-threaded; we could add a threading option to this, but please open that issue in django/channels issues.

Daphne itself is fully asynchronous and does not need threading.
