### ISSUE TITLE
Support full configuration through command line parameters

### ISSUE THREAD

**Issue by edevil** [django/daphne#71]
When deploying my apps to production I usually build containers, and I was expecting to be able to separate the interface servers containers from the workers containers, since they have only the channel layer configuration in common. However, it seems Daphne relies exclusively on the channel layer configuration as can be found on the Django settings.

It seems to me that it should be possible to also pass the needed layer configuration through command line parameters to daphne, and this way have a completely independent package with no need to include application code.

**Comment by andrewgodwin** [comment]
This isn't possible as the channel layer configuration requires instantiation of a Python class with non-textural arguments, You can make a single `asgi.py` file with just the channel layer instantiated and nothing else if you wish, which won't depend on application code, but you need something.
