### ISSUE TITLE
Receiving a "WebSocket connection denied: origin 'file://' not allowed" HTTP 400 response when initiating a Websocket connection from a Cordova/PhoneGap app

### ISSUE THREAD

**Issue by davidmarquis** [django/daphne#72]
I'm opening this issue to document what was originally posted to the Django Channels project but after investigation deemed related to Daphne itself:
https://github.com/django/channels/issues/392

In short, when running a Cordova/PhoneGap app on Android, the app runs within an embedded browser in a web view. When initiating a Websocket connection to Daphne, the browser sends an `Origin: file://` header on the initial request, which gets refused by Daphne. 

Investigation uncovered that Autobahn (the underlying Websocket library used by Daphne) refuses the connection because the value `file://` is considered invalid - more precisely, it is considered as if [no origin was provided](https://github.com/crossbario/autobahn-python/blob/master/autobahn/websocket/protocol.py#L2680).

Autobahn does allow the `Origin: file://` to be accepted, but for that to happen the `allowNullOrigin` protocol configuration option must be set to `True`.

As suggested by @andrewgodwin on the original issue, I'm going to work on a change to Daphne that will enable that flag by default, and pass the `Origin` header value to Channels in the `websocket.connect` message headers so that the application can decide wether or not a specific origin is allowed.

**Comment by andrewgodwin** [comment]
That PR looks good - I've merged it in, I'll issue a new release soon.

**Comment by davidmarquis** [comment]
Alright, thanks Andrew!
