### ISSUE TITLE
Daphne health-check

### ISSUE THREAD

**Issue by edevil** [django/daphne#77]
It would be nice for Daphne to support an endpoint that would allow an health check on itself and the channel layer subsystem, with no need for active workers. Maybe send a message on a predefined channel and check if it receives it?

Right now, when we launch the Daphne component, there's no URL that I know of that we can query to check if just the Daphne component is healthy. We need active workers to respond to request, and so it's harder to diagnose a problem.

**Comment by robmoorman** [comment]
The healthcheck would also be prefeffered in case you use Amazon ECS. A http health check is required to check whether daphne is health or not.

**Comment by robmoorman** [comment]
https://github.com/django/channels/blob/master/docs/getting-started.rst#first-consumers will do the trick though 👍

**Comment by andrewgodwin** [comment]
As of Daphne 2.0 the application is in-process so you can get a health check with a simple Django view.
