### ISSUE TITLE
Channels stopped working after twited update to 17

### ISSUE THREAD

**Issue by jorrete** [django/daphne#82]
While developing, I bulk update all my requirements, twisted updated to 17.1.0 and stopped to answer to the request. After downgrading twisted to 16.6.0 everything back to normal.
I hope I filled the bug in the right place.

**Comment by andrewgodwin** [comment]
1) Can I get some more details? Like what errors are printed on the console?
2) Have you looked at https://github.com/django/daphne/issues/78 - it could be that?

**Comment by wsot** [comment]
I'm experiencing the same problem using the example from the example on `Getting started with Channels`.

There are no errors in the logs, but when using Twisted 17.1.0 the `ws_message` function (registered as a route for `websocket.receive`) is not called at all. With Twisted 16.6.0 the function is called and responds as expected.
The console output from Django runserver looks identical in both cases (except that possibly with Twisted 17.1.0 there is a `WebSocket DISCONNECT /chat/` sooner, perhaps?)

**Comment by wsot** [comment]
[channels.twisted.17vs16.txt](https://github.com/django/daphne/files/769213/channels.twisted.17vs16.txt)

Attached is the output from the same example using Twisted 16.6.0 and 17.1.0. I added a log output to the function that should be called on a message received from the client, and output only occurred when using 16.6.0. (I also put a pudb set_trace in the function and it was only triggered in 16.6.0 also)

**Comment by andrewgodwin** [comment]
OK, that sounds eerily familiar with something we fixed six months ago for a different version of Twisted.

Can I ask what your versions of the following are?

* channels
* daphne
* asgiref
* asgi_redis
* Django
* Python

**Comment by andrewgodwin** [comment]
Nevermind, I've verified that upgrading to Twisted 17.1 just fails entirely. Looking for a fix now; in the meantime, I suggest using Twisted 16.6.

**Comment by andrewgodwin** [comment]
Fixed and released in Daphne 1.0.3.
