### ISSUE TITLE
parse_x_forwarded_for uses wrong IP from X-Forwarded-For

### ISSUE THREAD

**Issue by JohnDoee** [django/daphne#86]
Currently Daphne uses the right-most IP when parsing `X-Forwarded-For` while the original client would be the left-most IP.

See: [Wikipedia](https://en.wikipedia.org/wiki/X-Forwarded-For#Format) and [Twisted implementation](https://github.com/twisted/twisted/blob/e920939343ac5f6795c4509e0fe25c33a2447531/src/twisted/web/http.py#L2361-L2362).

**Comment by millerf** [comment]
I have the same problem. Has that been fixed?
