### ISSUE TITLE
module names bug with "_" (underscore)

### ISSUE THREAD

**Issue by millerf** [django/daphne#87]
I had an issue starting the server where the app was called "mzk_cloudserver"

I had to rename the app "mzk_cloudserver"to be able to run daphne...

**Comment by andrewgodwin** [comment]
Could you provide a traceback of what happened?

**Comment by millerf** [comment]
https://gist.github.com/millerf/4959acf22b5f2c43d2411fef7e1255a6

After renaming the folder and all "dependencies" it worked fine...

**Comment by andrewgodwin** [comment]
It looks like your settings file referred to `mzk_cloudserver`, while your project was in a folder called `mzkcloudserver`. I wouldn't say it was a Daphne bug; Daphne clearly managed to import your `asgi.py` file and start booting Django.
