### ISSUE TITLE
parse_x_forwarded_for fails with IPv6 addresses

### ISSUE THREAD

**Issue by cbay** [django/daphne#90]
When `X-Forwarded-Proto` contains an IPv6 (e.g. `2001:db8:85a3::8a2e:370:7334`), it raises the following traceback:

```
Traceback (most recent call last):
  File "/home/foo/env/local/lib/python2.7/site-packages/daphne/http_protocol.py", line 77, in process
    self.client_addr
  File "/home/foo/env/local/lib/python2.7/site-packages/daphne/utils.py", line 37, in parse_x_forwarded_for
    address_host, address_port = address_value.split(':')
ValueError: too many values to unpack
```

Since `X-Forwarded-Proto` is not standard, I don't have a sane suggestion on how to handle both IPv6 and ports. It seems that IPv6 is much more common than including the port in that header. For instance:

* AWS: http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html#x-forwarded-for
* Cloudflare: https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-

I'm using nginx, for the record.

**Comment by andrewgodwin** [comment]
I presume you were talking about `X-Forwarded-For`, as `Proto` contains the HTTP/HTTPS signifier instead. I have changed it so IPv6 addresses are supported and ports are not (unless you also use `X-Forwarded-Port`), since I can't find examples of stuff putting the port in there.

**Comment by cbay** [comment]
Indeed. Thanks!
