### ISSUE TITLE
Daphne write log in file

### ISSUE THREAD

**Issue by MarvinMuuss** [django/daphne#95]
Hey there!

We're using Daphne and Channels in production already and it works fine! 

We would like to print the log from daphne in an external file. Currently we're using this command:
daphne -u /tmp/daphne.sock django_project.asgi:channel_layer

is there any flag that can point to a file where daphne prints its log?

Many thanks in advance!

Cheers from Austria
Marvin

**Comment by andrewgodwin** [comment]
If you want a verbose access log, use the `--access-log` command line switch and give it a filename; if you want to just log the output of what Daphne prints to the console normally, then use shell redirection or a daemon runner (like supervisor, upstart, systemd etc.) and they'll support doing that.
