### ISSUE TITLE
Unable to run daphne with binding command

### ISSUE THREAD

**Issue by Muhammad-Soban** [django/daphne#97]
using python manage.py runserver i am able to establish successful websocket connection. but when i run the following command
```
daphne -b 0.0.0.0 -p 8001 app_name.asgi:channel_layer
```
the server is successfully started but the connection fails as shown below. i am unable to find a solution for this.
```
2017-03-22 10:40:11,940 INFO     Starting server at tcp:port=8001:interface=0.0.0.0, channel layer app_name.asgi:channel_layer.
2017-03-22 10:40:11,940 INFO     Using busy-loop synchronous mode on channel layer
2017-03-22 10:40:11,940 INFO     Listening on endpoint tcp:port=8001:interface=0.0.0.0
127.0.0.1:53259 - - [22/Mar/2017:10:40:33] "WSCONNECTING /ws/2" - -
127.0.0.1:53259 - - [22/Mar/2017:10:40:38] "WSDISCONNECT /ws/2" - -

```
below is the client code.
```
let socket = new WebSocket("ws://" + "localhost:8001" + "/ws/2");
socket.onmessage = function(e) {
    alert(e.data);
};
socket.onopen = function() {
    console.log("onOpen")
};

if (socket.readyState == WebSocket.OPEN) {
    socket.onopen();
}
```
Error is
```
WebSocket connection to 'ws://localhost:8001/ws/2' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET
```

**Comment by andrewgodwin** [comment]
Are you accepting the connection in the `connect` handler? http://channels.readthedocs.io/en/latest/releases/1.0.0.html#connect-consumers

**Comment by Muhammad-Soban** [comment]
Yes i am accepting the connection in the connect handler as:
```
def ws_connect(message):
    print(message.content['path'])
    group_name = str(message.content['path'][4:])
    Group(group_name).add(message.reply_channel)
    message.reply_channel.send({"accept": True})
```

**Comment by andrewgodwin** [comment]
Weird - the log you posted shows that the socket never goes into fully connected state, so it was either the request not being accepted right or a problem with the TCP communication. Have you tried with a different browser?

**Comment by Muhammad-Soban** [comment]
I have fixed this issue by running following command in second terminal.
```
python manage.py runworker
```
more: https://channels.readthedocs.io/en/stable/deploying.html#run-interface-servers
