### ISSUE TITLE
SocketRocket client with a Daphne websocket server disconnecting websocket on client side

### ISSUE THREAD

**Issue by yabenatti** [django/daphne#98]
I am developing an iOS app in Objective-C, on XCode Version 8.2.1 and I'm using SocketRocket through cocoapods. 

update: My backend uses Daphne (1.1.0), cloudflare and nginx (1.10.2). So the calls are done like it follows:
User -> CF -> Nginx -> Daphne

After successfully connecting and receiving data from the websocket, the connection is closed with the reason "Stream end encountered". It doesn't happen every time I connect with the websocket though. The output of the method "(void)webSocket:(SRWebSocket *)webSocket didCloseWithCode:" is as it follows:

"WebSocket closed reason: Stream end encountered and code: 1001 and was clean: 0"

Have someone had that problem before?

**Comment by andrewgodwin** [comment]
WebSockets close for a number of reasons - if Daphne did it for an unusual reason (say ping timeout) it would tell you on its console.

Code 1001, though, means (as it says) that it was closed cleanly, which means you must have send a `close` packet from your application - or, that something in the stack (likely CloudFlare) did instead. How long is it staying open for each time, and are you leaving it idle when it closes?

**Comment by yabenatti** [comment]
We have pined down that the problem is on the back-end side but couldn't find out the exact problem yet. 
It usually stays open for about a minute.

I'll comeback with more information when I have something more concrete. 

Thank you for the answer, though

**Comment by seocam** [comment]
We've added a different domain to the same server and the problem stops occurring. It's very likely to be a CloudFlare issue since different domains have different configurations ans certs. I'm going to open an issue in their support.

**Comment by andrewgodwin** [comment]
Good to know - proxying WebSockets can be tough to do correctly. Let me know if you find anything that Daphne could do to improve the situation (we already send ping packets down the socket at regular intervals to try and stop proxies dropping it due to lack of data)
